-- Seed: 4 draft Photo Spot Library rows from Trip2Talk-Photo-Spots draft data.
-- Do NOT apply to production until Saen explicitly approves.
--
-- Trip codes:
--   bombo-headland, helensburgh-tunnel → KIA-1DAY
--   uluru-sunset → ULU-4D3N
--   cradle-dove-lake → TAS-3D2N

insert into public.photo_spots (
  id,
  slug,
  title_en,
  title_th,
  location_en,
  location_th,
  latitude,
  longitude,
  google_maps_url,
  best_time_morning,
  best_time_evening,
  best_time_night,
  access_private_car,
  access_public_transport,
  gear_landscape,
  gear_portrait,
  drone_allowed,
  drone_notes,
  linked_trip_code,
  photo_id,
  rating,
  sort_order
)
values
  (
    'a1111111-1111-4111-8111-111111111101',
    'bombo-headland',
    'Bombo Headland',
    'หน้าผาหินบะซอลต์ เมือง Kiama',
    'Kiama, NSW',
    'เกียม่า, นิวเซาท์เวลส์',
    -34.6721,
    150.8590,
    'https://maps.google.com/?q=Bombo+Headland+Quarry,+Kiama+NSW',
    'Sunrise 05:30–06:30 — แสงส้มทองกระทบหน้าผาโดยตรง ช่วง มี.ค.–พ.ค. คลื่นเบาที่สุด',
    'ไม่แนะนำ — หน้าผาหันทิศตะวันออก แสงเย็นไม่กระทบผิวหิน',
    null,
    'จอดรถที่ Bombo Quarry Car Park เดินเท้า 5 นาทีถึงจุดถ่าย พื้นเป็นหินไม่เรียบ',
    'รถไฟสาย South Coast Line ลงสถานี Kiama เดินต่อ 15 นาที',
    'เลนส์มุมกว้าง (14–24mm), ขาตั้งกล้อง, ND filter สำหรับ Long Exposure จับจังหวะคลื่น',
    'เลนส์ 35–50mm, ไม่จำเป็นต้องมีรีเฟล็กเตอร์ถ้าถ่ายตอนเช้า แสงนุ่มอยู่แล้ว',
    'restricted',
    'จำกัด — ตรวจกฎ CASA และพื้นที่ใกล้เคียงก่อนบิน อย่าบินเหนือคน / ใกล้คลื่นแรง',
    'KIA-1DAY',
    'ber-001',
    4.9,
    10
  ),
  (
    'a1111111-1111-4111-8111-111111111102',
    'uluru-sunset',
    'Uluru Sunset Viewing Area',
    'จุดชมพระอาทิตย์ตกอูลูรู',
    'Uluru-Kata Tjuta National Park, NT',
    'อุทยานแห่งชาติอูลูรู-กาตาจูตา, นอร์เทิร์นเทร์ริทอรี',
    -25.3444,
    131.0369,
    'https://maps.google.com/?q=Uluru+Sunset+Viewing+Area',
    'Sunrise ที่จุด Talinguru Nyakunytjaku ดีกว่าจุดนี้ — ดูพิกัด "Uluru Sunrise" แยก',
    'Golden Hour 17:30–18:15 (หน้าร้อน) / 17:00–17:45 (หน้าหนาว) — หินเปลี่ยนจากส้มเป็นแดงเข้ม',
    'หลัง 20:00 ท้องฟ้ามืดสนิท — เช็คเมฆที่ BOM Radar และเช็คเฟสดวงจันทร์ที่ PhotoPills ก่อนไปเสมอ ควรเลือกคืนจันทร์แรม/ใกล้จันทร์ดับเพื่อเห็นทางช้างเผือกชัดสุด',
    'จอดที่ Sunset Viewing Car Park ในอุทยาน เดินเท้าเกือบไม่ต้องเดิน (จอดติดจุดชม)',
    null,
    'เลนส์มุมกว้าง 16–35mm, ขาตั้งกล้อง (ลมแรงตอนเย็น), โพลาไรซ์ฟิลเตอร์ตัดแสงสะท้อน',
    'เลนส์ 85mm ถ่ายย้อนแสง silhouette กับหินอูลูรู, รีเฟล็กเตอร์สีทองช่วยเสริมแสง',
    'prohibited',
    'ห้ามเด็ดขาดตามกฎหมาย — โดรนถูกแบนในอุทยานแห่งชาติอูลูรู-กาตาจูตา มีโทษปรับ ห้ามบินโดยเด็ดขาด',
    'ULU-4D3N',
    'tas-002',
    4.9,
    20
  ),
  (
    'a1111111-1111-4111-8111-111111111103',
    'cradle-dove-lake',
    'Cradle Mountain — Dove Lake',
    'เครเดิลเมาน์เทน ทะเลสาบโดฟ',
    'Cradle Mountain-Lake St Clair National Park, TAS',
    'อุทยานแห่งชาติเครเดิลเมาน์เทน, แทสเมเนีย',
    -41.6398,
    145.9375,
    'https://maps.google.com/?q=Dove+Lake,+Cradle+Mountain+TAS',
    'Sunrise 06:00–07:00 (หน้าร้อน) — น้ำนิ่งสะท้อนภูเขาชัดที่สุดก่อนลมแรง',
    'Golden Hour 17:30–18:30 — แสงทองกระทบยอดเขา',
    'Aurora Australis เฉพาะคืนที่ KP Index สูง — เช็คเมฆที่ BOM Radar และเช็คเฟสดวงจันทร์ที่ PhotoPills ก่อนเสมอ (จันทร์เต็มดวงจะกลบแสงเหนือ/ใต้ให้จางลงมาก)',
    'จอดที่ Dove Lake Car Park เดินรอบทะเลสาบ 6 กม. (2 ชม.) หรือถ่ายจากจุดจอดรถได้เลยถ้าเวลาจำกัด',
    'Cradle Mountain Shuttle Bus จากศูนย์บริการนักท่องเที่ยว (ไม่มีรถไฟ/รถเมล์ทั่วไปเข้าถึง)',
    'เลนส์มุมกว้าง 14–24mm, ขาตั้งกล้อง, เสื้อกันหนาวหนา (อากาศเปลี่ยนไวมาก)',
    null,
    'restricted',
    'จำกัด — ต้องปฏิบัติตามกฎ Parks Tasmania / ขออนุญาตก่อนบินในพื้นที่อุทยาน',
    'TAS-3D2N',
    'tas-107',
    4.8,
    30
  ),
  (
    'a1111111-1111-4111-8111-111111111104',
    'helensburgh-tunnel',
    'Helensburgh Old Railway Tunnel',
    'อุโมงค์รถไฟร้าง เฮเลนส์เบิร์ก',
    'Helensburgh, NSW',
    'เฮเลนส์เบิร์ก, นิวเซาท์เวลส์',
    -34.1848,
    150.9975,
    'https://maps.google.com/?q=Helensburgh+Tunnel+Glow+Worm',
    null,
    null,
    'หลังพระอาทิตย์ตก — หนอนเรืองแสง (glow worms) เห็นชัดสุดในความมืดสนิท ต้องรอตาปรับแสงอย่างน้อย 10 นาที',
    'จอดที่ลานจอดใกล้ทางเข้า เดินเท้าในป่าประมาณ 15 นาทีถึงปากอุโมงค์ พื้นดินลื่นเมื่อฝนตก',
    'รถไฟสาย South Coast Line ลงสถานี Helensburgh เดินต่อ 20 นาที',
    'เลนส์รูรับแสงกว้าง f/1.8–f/2.8, ISO สูง 3200+, ไฟฉายส่องทางเดิน (ปิดก่อนถ่าย)',
    'ไม่แนะนำแฟลชแรง (รบกวนหนอนเรืองแสง), ใช้ไฟนวลอ่อนหรือถ่ายแบบ silhouette แทน',
    'restricted',
    'ไม่เหมาะ — อุโมงค์ปิดทึบ (enclosed space) โดรนใช้ไม่ได้ในจุดนี้',
    'KIA-1DAY',
    'syd-015',
    4.7,
    40
  )
on conflict (id) do update set
  slug = excluded.slug,
  title_en = excluded.title_en,
  title_th = excluded.title_th,
  location_en = excluded.location_en,
  location_th = excluded.location_th,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  google_maps_url = excluded.google_maps_url,
  best_time_morning = excluded.best_time_morning,
  best_time_evening = excluded.best_time_evening,
  best_time_night = excluded.best_time_night,
  access_private_car = excluded.access_private_car,
  access_public_transport = excluded.access_public_transport,
  gear_landscape = excluded.gear_landscape,
  gear_portrait = excluded.gear_portrait,
  drone_allowed = excluded.drone_allowed,
  drone_notes = excluded.drone_notes,
  linked_trip_code = excluded.linked_trip_code,
  photo_id = excluded.photo_id,
  rating = excluded.rating,
  sort_order = excluded.sort_order,
  updated_at = now();
