-- Photo Spots — New Zealand South Island seed (Phase 1 follow-up).
-- Idempotent upsert of 4 verified NZ locations linked to NZ-6D5N.
-- Requires photo_spots Phase 1 schema (20260810120000_photo_spots_phase1.sql).

insert into public.photo_spots (
  id, slug, title_en, title_th, location_en, location_th,
  latitude, longitude, google_maps_url,
  description_en, description_th,
  categories, best_time, best_season, drive_time_from_sydney,
  best_time_morning, best_time_evening, best_time_night,
  access_private_car, access_public_transport,
  gear_landscape, gear_portrait,
  camera_settings, tips_en, tips_th, warnings_en, warnings_th,
  drone_allowed, drone_notes,
  linked_trip_code, related_trip_code, photo_id,
  rating, sort_order, is_featured, review_notes
)
values
  (
    'a1111111-1111-4111-8111-111111111201',
    'lake-tekapo-good-shepherd',
    'Lake Tekapo — Church of the Good Shepherd',
    'ทะเลสาบเทคาโป — โบสถ์ Church of the Good Shepherd',
    'Lake Tekapo, Mackenzie District, NZ',
    'ทะเลสาบเทคาโป, เขตแมคเคนซี, นิวซีแลนด์',
    -44.00333, 170.48250,
    'https://maps.google.com/?q=Church+of+the+Good+Shepherd,+Lake+Tekapo',
    'Iconic lakeside stone church on Lake Tekapo inside the Aoraki Mackenzie International Dark Sky Reserve — a classic South Island night-sky and daytime landscape stop.',
    'โบสถ์หินริมทะเลสาบเทคาโปในเขตมืดนานาชาติ Aoraki Mackenzie — จุดคลาสสิกทั้งกลางวันและท้องฟ้ามืดเกาะใต้',
    array['Night','Milky Way','Landscape','Portrait'],
    'Clear nights (dark sky) / soft daytime lake light',
    'Year-round; clearest winter nights often best for Milky Way (verify cloud)',
    'Flight SYD→CHC (~3 hrs) + ~3–3.5 hrs drive — not a Sydney day drive',
    'Soft morning light on the church and lake when skies are clear.',
    'Blue hour into dusk — church silhouette against lake and mountains.',
    'After full dark on clear, moonless nights — Aoraki Mackenzie is an International Dark Sky Reserve. Check cloud + moon phase; do not use bright lights on other visitors.',
    'Park in the public car parks near Pioneer Drive / church precinct and walk a short distance to the lakeshore viewing areas. Stay off private property and respect church grounds.',
    null,
    'Wide lens + tripod for night sky; dress for alpine cold and wind.',
    '35–85mm for people with church/lake backdrop — keep paths clear for other visitors.',
    '{"landscape":{"aperture":"f/2.8–f/4 (night) / f/8–f/11 (day)","iso":"1600–6400 (night) / 100–200 (day)","shutter":"10–25s (night, track stars carefully) / 1/60–1/125 (day)","filter":null},"portrait":{"aperture":"f/2.8–f/5.6","iso":"200–1600","shutter":"1/160+","filter":null}}'::jsonb,
    'Arrive early for night sessions; keep red/low light only; never block doorways during services. Related Trip2Talk trip: NZ-6D5N (NZ-10D9N also covers Mackenzie).',
    'มาถึงก่อนมืด ใช้ไฟแดง/ไฟอ่อน และอย่าขวางทางเข้าโบสถ์ตอนมีพิธี ทริปที่เกี่ยวข้อง: NZ-6D5N',
    'Respect church grounds and quiet hours. Cold wind off the lake. Dark-sky etiquette — no bright white lights or lasers. Confirm any local access notices. REVIEW: pin is church location (Wikipedia/Wikidata).',
    'เคารพพื้นที่โบสถ์ อากาศหนาวลมแรงจากทะเลสาบ ไม่ใช้ไฟขาวแรง/เลเซอร์ [REVIEW พิกัดโบสถ์]',
    'restricted',
    'Follow CAA NZ rules; avoid flying over people and near the church precinct.',
    'NZ-6D5N', 'NZ-6D5N', 'nz-001',
    4.9, 50, true,
    'Hero photo_id is generic NZ cover — swap to a Tekapo frame when available. Exact night shutter/ISO ranges are starting points for Saen review.'
  ),
  (
    'a1111111-1111-4111-8111-111111111202',
    'aoraki-hooker-valley',
    'Aoraki / Mount Cook — Hooker Valley',
    'ออรากิ / เมาท์คุก — หุบเขาฮุคเกอร์',
    'Aoraki/Mount Cook National Park, Canterbury, NZ',
    'อุทยานแห่งชาติออรากิ/เมาท์คุก, แคนเทอร์เบอรี, นิวซีแลนด์',
    -43.7187, 170.09315,
    'https://maps.google.com/?q=Hooker+Valley+Track,+Aoraki+Mount+Cook',
    'DOC Hooker Valley Track trailhead area with classic valley views toward Aoraki/Mount Cook — one of New Zealand’s most photographed alpine landscapes.',
    'จุดเริ่มเส้นทาง Hooker Valley ของ DOC ที่มองเห็นหุบเขาและยอดออรากิ/เมาท์คุก — วิวอัลไพน์คลาสสิกของนิวซีแลนด์',
    array['Landscape','Nature','Sunrise','Portrait'],
    'Golden hour / clear alpine light on the peaks',
    'Shoulder seasons often clearer; check DOC alerts year-round',
    'Flight SYD→CHC + drive via Twizel/SH80 — multi-day NZ itinerary',
    'Morning light into the valley when cloud is off the peaks.',
    'Late light on Aoraki/Mount Cook when skies are clear — weather changes fast.',
    null,
    'Drive Hooker Valley Road to White Horse Hill car park (DOC). Track starts from the car park area — follow DOC signs.',
    null,
    'Wide to standard zoom + poles/layers; alpine weather kit essential.',
    'People-with-mountain frames work mid-tele — stay on marked track.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/60–1/250 (tripod if wind drops)","filter":"CPL optional — REVIEW"},"portrait":{"aperture":"f/2.8–f/5.6","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Check DOC Hooker Valley Track status before going (closures happen). Related trip: NZ-6D5N / NZ-10D9N South Island legs.',
    'เช็คสถานะเส้นทาง DOC ก่อนไปเสมอ ทริปที่เกี่ยวข้อง: NZ-6D5N / NZ-10D9N',
    'Alpine weather, glacial rivers, and sudden cloud/wind. Stay on the marked track and bridges. Recreational drones in national parks typically need DOC authorisation — do not assume you can fly. REVIEW GPS = White Horse Hill / Hooker Valley trailhead.',
    'อากาศอัลไพน์ แม่น้ำธารน้ำแข็ง เมฆ/ลมเปลี่ยนไว เดินตามทาง DOC โดรนในอุทยานมักต้องขออนุญาต [REVIEW พิกัดจุดจอด]',
    'restricted',
    'DOC national park — permits usually required; follow current park rules.',
    'NZ-6D5N', 'NZ-6D5N', 'nz-013',
    4.9, 60, true,
    'Track can close — keep warnings current. Hero photo_id is generic NZ — swap when Mount Cook frame is tagged.'
  ),
  (
    'a1111111-1111-4111-8111-111111111203',
    'lake-pukaki-peters-lookout',
    'Lake Pukaki — Peter''s Lookout',
    'ทะเลสาบพูคากิ — จุดชมวิว Peter’s Lookout',
    'Mount Cook Road (SH80), near Lake Pukaki, NZ',
    'ถนน Mount Cook (SH80) ใกล้ทะเลสาบพูคากิ, นิวซีแลนด์',
    -44.1901, 170.1398,
    'https://maps.google.com/?q=Peter''s+Lookout+Lake+Pukaki',
    'Signed roadside lookout on SH80 with turquoise Lake Pukaki and mountain backdrop toward Aoraki/Mount Cook — a classic blue-hour / golden-hour pull-over.',
    'จุดชมวิวริมถนน SH80 กับน้ำสีฟ้าของทะเลสาบพูคากิและฉากหลังภูเขาไปทางออรากิ — จุดจอดคลาสสิกช่วงฟ้าคราม/golden hour',
    array['Landscape','Sunrise','Sunset','Nature'],
    'Blue hour / golden hour on clear days',
    'Year-round; clearest views when peaks are free of low cloud',
    'Flight SYD→CHC + drive on SH80 toward Mount Cook Village',
    'Sunrise/blue hour looking up the lake toward the mountains.',
    'Golden hour when light hits the ranges — watch road traffic.',
    null,
    'Pull into the signed Peter’s Lookout / Tapataia Mahaka car park on Mount Cook Road (SH80). Short walk to viewing areas; stay clear of the highway.',
    null,
    'Wide to mid zoom; CPL can help manage lake glare — REVIEW preference.',
    'People against lake/mountain — keep clear of the road edge.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–1/125","filter":"CPL optional — REVIEW"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'SH80 is a busy tourist road — park fully off the lane. Related trip: NZ-6D5N.',
    'SH80 รถเยอะ — จอดให้พ้นเลน ทริปที่เกี่ยวข้อง: NZ-6D5N',
    'Highway traffic hazard — do not stop on the road itself. Wind off the lake can be cold. GPS pin is approximate for the lookout precinct — REVIEW exact car-park pin with Saen.',
    'อันตรายจากรถบนทางหลวง อย่าจอดบนถนน ลมหนาวจากทะเลสาบ [REVIEW พิกัดลานจอด]',
    'restricted',
    'CAA NZ rules; avoid flying over roads, cars, and people.',
    'NZ-6D5N', 'NZ-6D5N', 'nz-014',
    4.8, 70, false,
    'Confirm exact Peter’s Lookout car-park coordinates before treating pin as surveyed. Hero media generic NZ for now.'
  ),
  (
    'a1111111-1111-4111-8111-111111111204',
    'that-wanaka-tree',
    'That Wānaka Tree',
    'ต้นไม้ That Wānaka Tree',
    'Lake Wānaka, Otago, NZ',
    'ทะเลสาบวานากา, โอทาโก, นิวซีแลนด์',
    -44.6983, 169.1175,
    'https://maps.google.com/?q=That+Wanaka+Tree',
    'Lone willow standing in the shallows of Lake Wānaka — one of New Zealand’s most photographed trees (sunrise/sunset + portrait favourite).',
    'ต้นวิลโลว์เดียวกลางน้ำตื้นของทะเลสาบวานากา — จุดถ่ายภาพยอดนิยมทั้งพระอาทิตย์ขึ้น/ตกและพอร์ตเทรต',
    array['Landscape','Portrait','Sunrise','Sunset'],
    'Sunrise / sunset (calm water helps)',
    'Year-round; calm mornings often cleaner reflections',
    'Flight SYD→CHC/ZQN + drive to Wānaka — multi-day NZ itinerary',
    'Sunrise when the lake is calm — reflections of the tree and sky.',
    'Sunset / blue hour — expect crowds; be patient and share the shore.',
    null,
    'Park near Wanaka Station Park / lakeside walkway access and walk along the public shore path to the tree viewpoint. Do not drive onto the foreshore.',
    null,
    'Wide to mid zoom; waterproof footwear for damp shore edges.',
    'Popular for couples/portraits — keep space for other visitors; no climbing the tree.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–1/125 (ND if smoothing water — REVIEW)","filter":"ND / CPL optional — REVIEW"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Share the viewpoint; do not climb or damage the tree. Related trip: NZ-6D5N (Wanaka/Queenstown region also on NZ-10D9N).',
    'แชร์มุมถ่าย อย่าปีน/ทำลายต้นไม้ ทริปที่เกี่ยวข้อง: NZ-6D5N',
    'Slippery rocks and cold water at the shore. Respect the tree — climbing/damage has been a real issue. Crowds at peak sunrise/sunset. Coords from Wikipedia / NZ Tree Register.',
    'หินลื่น น้ำเย็น อย่าปีนต้นไม้ คนหนาแน่นตอนพระอาทิตย์ขึ้น/ตก',
    'restricted',
    'CAA NZ rules; avoid flying over crowds on the foreshore.',
    'NZ-6D5N', 'NZ-6D5N', 'nz-015',
    4.8, 80, true,
    'Hero photo_id is generic NZ — prefer a real Wanaka-tree frame when tagged. Cardrona Valley not seeded separately; Wanaka tree is the verified public pin.'
  )
on conflict (id) do update set
  slug = excluded.slug,
  title_en = excluded.title_en,
  title_th = excluded.title_th,
  location_en = excluded.location_en,
  location_th = excluded.location_th,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  google_maps_url = excluded.google_maps_url,
  description_en = excluded.description_en,
  description_th = excluded.description_th,
  categories = excluded.categories,
  best_time = excluded.best_time,
  best_season = excluded.best_season,
  drive_time_from_sydney = excluded.drive_time_from_sydney,
  best_time_morning = excluded.best_time_morning,
  best_time_evening = excluded.best_time_evening,
  best_time_night = excluded.best_time_night,
  access_private_car = excluded.access_private_car,
  access_public_transport = excluded.access_public_transport,
  gear_landscape = excluded.gear_landscape,
  gear_portrait = excluded.gear_portrait,
  camera_settings = excluded.camera_settings,
  tips_en = excluded.tips_en,
  tips_th = excluded.tips_th,
  warnings_en = excluded.warnings_en,
  warnings_th = excluded.warnings_th,
  drone_allowed = excluded.drone_allowed,
  drone_notes = excluded.drone_notes,
  linked_trip_code = excluded.linked_trip_code,
  related_trip_code = excluded.related_trip_code,
  photo_id = excluded.photo_id,
  rating = excluded.rating,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  review_notes = excluded.review_notes,
  updated_at = now();
