-- Photo Spots bulk seed — curated AU + NZ locations (2026-08-10)
-- Idempotent upsert by slug. Merges enrich existing Phase 1 / NZ rows;
-- new rows leave hero/gallery empty for staff upload via /app/spots.
-- Requires: 20260810120000_photo_spots_phase1 + 20260810150000_photo_spots_staff_bucket.

insert into public.photo_spots (
  id, slug, title_en, title_th, location_en, location_th,
  latitude, longitude, google_maps_url,
  description_en, description_th,
  categories, best_time, best_season, drive_time_from_sydney,
  access_private_car, access_public_transport,
  gear_landscape, gear_portrait,
  camera_settings, tips_en, tips_th, warnings_en, warnings_th,
  drone_allowed, drone_notes,
  linked_trip_code, related_trip_code,
  rating, sort_order, is_featured, review_notes,
  hero_image_url, thumbnail_url, gallery_image_urls
)
values
(
    'a1111111-1111-4111-8111-111111111101'::uuid,
    'bombo-headland',
    'Bombo Headland Quarry',
    'เหมืองหินหน้าผาบอมโบ (Kiama)',
    'Kiama, NSW',
    'เกียม่า, นิวเซาท์เวลส์',
    -34.6721, 150.859,
    'https://maps.google.com/?q=Bombo+Headland+Quarry,+Kiama+NSW',
    'East-facing basalt columns and quarry platforms near Kiama — classic NSW south-coast sunrise landscape and portrait backdrop.',
    'หน้าผาหินบะซอลต์และแท่นเหมืองหันทิศตะวันออกใกล้เกียม่า — จุดพระอาทิตย์ขึ้นคลาสสิกชายฝั่งใต้ NSW',
    array['Landscape','Portrait','Coastal','Sunrise'],
    'Sunrise (east-facing cliffs)',
    'Year-round; calmer seas often easier Mar–May (verify swell)',
    '~1.5–2 hrs from Sydney',
    'Park at Bombo Quarry / headland car park and walk carefully onto uneven basalt. Surfaces can be wet and sharp.',
    'South Coast Line to Kiama, then local walk/taxi (~15–25 min).',
    'Wide lens + tripod; ND useful when swell allows safe positioning.',
    '35–50mm for people against the columns in soft morning light.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND / CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Arrive before sunrise; never turn your back on the ocean on wet platforms.',
    'มาถึงก่อนพระอาทิตย์ขึ้น — อย่าหันหลังให้ทะเลบนพื้นหินเปียก',
    'Uneven basalt, slippery when wet. Large swell can wash over rock platforms — check marine forecast. [REVIEW: confirm any local access/parking notices before publishing as advice.]',
    'พื้นหินลื่นเมื่อเปียก คลื่นใหญ่ซัดขึ้นแท่นได้ — เช็คพยากรณ์ทะเล [REVIEW: ยืนยันป้าย/การเข้าถึงท้องถิ่น]',
    'restricted',
    'Follow CASA rules; avoid flying over people or close to breaking surf.',
    'KIA-1DAY',
    'KIA-1DAY',
    4.9,
    10,
    true,
    'Merged from curated list #36 Bombo Headland Quarry. Camera ranges and swell wording need Saen review.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111104'::uuid,
    'helensburgh-tunnel',
    'Helensburgh Old Station & Railway Tunnel',
    'สถานีเก่าและอุโมงค์รถไฟเฮเลนส์เบิร์ก',
    'Helensburgh, NSW',
    'เฮเลนส์เบิร์ก, นิวเซาท์เวลส์',
    -34.1848, 150.9975,
    'https://maps.google.com/?q=Helensburgh+Tunnel+Glow+Worm',
    'Disused railway tunnel and old station precinct south of Sydney — known for glow-worm displays in near-total darkness.',
    'อุโมงค์รถไฟร้างและย่านสถานีเก่าทางใต้ซิดนีย์ — มีหนอนเรืองแสงในความมืดสนิท',
    array['Night','Milky Way','Landscape','Portrait'],
    'After dark (glow worms)',
    'Year-round; best after full dark',
    '~50–60 min from Sydney',
    'Park near the commonly used trailhead and walk in on a bush track (~10–20 min). Track can be muddy after rain.',
    'South Coast Line to Helensburgh station, then walk (~20 min depending on route).',
    'Fast lens (f/1.8–f/2.8), high ISO, tripod. Torch for the walk only.',
    'Avoid strong flash (disturbs glow worms). Soft light or silhouette approaches.',
    '{"landscape":{"aperture":"f/1.8–f/2.8","iso":"3200–6400","shutter":"10–25s","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"1600–6400","shutter":"1/30–2s","filter":"no harsh flash"}}'::jsonb,
    'Stay on established paths; keep voices low; do not touch tunnel walls or glow-worm areas.',
    'เดินตามทางเดิม พูดเบา และอย่าแตะผนังอุโมงค์/หนอนเรืองแสง',
    'Muddy/slippery after rain. Confined dark space — torch for walking. [REVIEW: GPS pin + current public-access / land status with Saen.]',
    'ทางเข้าลื่นหลังฝน อุโมงค์มืด — พกไฟฉาย [REVIEW: พิกัดและการเข้าถึงสาธารณะ]',
    'restricted',
    'Not suitable — enclosed tunnel environment.',
    'KIA-1DAY',
    'KIA-1DAY',
    4.7,
    20,
    true,
    'Merged curated #33 Helensburgh Old Station. Access status needs ongoing review.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111102'::uuid,
    'uluru-sunset',
    'Uluru — Sunset & Sunrise Viewing Areas',
    'อูลูรู — จุดชมพระอาทิตย์ขึ้น/ตก',
    'Uluru-Kata Tjuta National Park, NT',
    'อุทยานแห่งชาติอูลูรู-กาตาจูตา, นอร์เทิร์นเทร์ริทอรี',
    -25.3444, 131.0369,
    'https://maps.google.com/?q=Uluru+Sunset+Viewing+Area',
    'Designated Parks Australia sunrise and sunset viewing areas for Uluru — rock colour shifts through golden hour on Aṉangu land.',
    'จุดชมพระอาทิตย์ขึ้น/ตกอย่างเป็นทางการของ Parks Australia สำหรับอูลูรู — สีหินเปลี่ยนชัดใน golden hour บนดินแดนของชาว Aṉangu',
    array['Landscape','Portrait','Sunset','Sunrise'],
    'Sunrise and sunset (designated car parks)',
    'Apr–Sep cooler/clearer; summer extreme heat',
    'Flight to AYQ + park transfer — not a Sydney drive',
    'Use only designated sunrise/sunset viewing areas and follow park road signs. Parks pass required.',
    null,
    'Wide–mid zoom + tripod; dust cover for sensor changes.',
    '85mm-ish for people with Uluru backdrop — stay behind barriers.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/60–1/200","filter":"CPL optional"},"portrait":{"aperture":"f/2.8–f/5.6","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Arrive early for parking. Stay behind barriers. Related trip: ULU-4D3N. Cultural respect: do not climb Uluru; follow photo restrictions for sacred sites.',
    'มาถึงก่อนเพื่อจอดรถ อยู่หลังแนวกั้น ทริป: ULU-4D3N — อย่าปีนอูลูรู และเคารพข้อห้ามถ่ายภาพพื้นที่ศักดิ์สิทธิ์',
    'Parks pass required. Extreme heat in summer — carry water. Climbing Uluru is permanently closed. Some cultural sites have photography restrictions — follow Parks Australia guidance. [REVIEW: exact sunrise vs sunset car-park pins if splitting later.]',
    'ต้องมีบัตรอุทยาน อากาศร้อนจัดในฤดูร้อน — พกน้ำ ห้ามปีนอูลูรู บางจุดมีข้อห้ามถ่ายภาพ [REVIEW: พิกัดจุด sunrise/sunset ถ้าจะแยกภายหลัง]',
    'prohibited',
    'Drones are not permitted in Uluru–Kata Tjuta National Park without authorisation.',
    'ULU-4D3N',
    'ULU-4D3N',
    4.9,
    30,
    true,
    'Merged curated #5 Uluru Sunset/Sunrise. Pin is sunset area — confirm sunrise area pin if needed.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111103'::uuid,
    'cradle-dove-lake',
    'Cradle Mountain — Dove Lake',
    'เครเดิลเมาน์เทน — ทะเลสาบโดฟ',
    'Cradle Mountain-Lake St Clair National Park, TAS',
    'อุทยานเครเดิลเมาน์เทน–ทะเลสาบเซนต์แคลร์, แทสเมเนีย',
    -41.64, 145.938,
    'https://maps.google.com/?q=Dove+Lake,+Cradle+Mountain',
    'Iconic Dove Lake circuit views of Cradle Mountain — Tasmania’s signature alpine landscape (shuttle from visitor centre often required in peak season).',
    'วิวทะเลสาบโดฟและยอดเครเดิลเมาน์เทน — แลนด์สเคปอัลไพน์สัญลักษณ์ของแทสเมเนีย (ช่วงพีคมักต้องใช้รถ shuttle)',
    array['Landscape','Nature','Aurora','Night'],
    'Golden hour / clear alpine light; aurora on dark clear nights',
    'Shoulder seasons often clearer; winter snow possible',
    '~1.5–2 hrs from Launceston / ~4 hrs from Hobart',
    'Parks pass required. Peak periods: park at visitor centre and take shuttle to Dove Lake. Check PWS alerts.',
    null,
    'Wide lens + weather protection; layers for alpine wind/rain.',
    'People-with-mountain frames — stay on boardwalk/track.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/60–1/250","filter":"CPL optional"},"portrait":{"aperture":"f/2.8–f/5.6","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Check shuttle timetable and weather before going. Related trip: TAS-3D2N.',
    'เช็คตาราง shuttle และอากาศก่อนไป ทริป: TAS-3D2N',
    'Alpine weather changes fast. Boardwalks can be icy. [REVIEW: current shuttle rules / oversnow conditions with PWS.]',
    'อากาศอัลไพน์เปลี่ยนไว ทางเดินอาจลื่นแข็ง [REVIEW: กฎ shuttle / หิมะกับ PWS]',
    'restricted',
    'National park — recreational drones typically need authorisation.',
    'TAS-3D2N',
    'TAS-3D2N',
    4.9,
    40,
    true,
    'Merged curated #31 Cradle Mountain. Enrich Dove Lake circuit notes as needed.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111201'::uuid,
    'lake-tekapo-good-shepherd',
    'Lake Tekapo — Church of the Good Shepherd',
    'ทะเลสาบเทคาโป — โบสถ์ Church of the Good Shepherd',
    'Lake Tekapo, Mackenzie District, NZ',
    'ทะเลสาบเทคาโป, เขตแมคเคนซี, นิวซีแลนด์',
    -44.00333, 170.4825,
    'https://maps.google.com/?q=Church+of+the+Good+Shepherd,+Lake+Tekapo',
    'Iconic lakeside church on Lake Tekapo inside the Aoraki Mackenzie International Dark Sky Reserve.',
    'โบสถ์ริมทะเลสาบเทคาโปในเขตมืดนานาชาติ Aoraki Mackenzie',
    array['Night','Milky Way','Landscape','Portrait'],
    'Clear nights (dark sky) / soft daytime lake light',
    'Year-round; winter nights often clearest for Milky Way (verify cloud)',
    '~3–3.5 hrs from Christchurch (or via Queenstown itinerary)',
    'Public car parks near Pioneer Drive / church precinct. Respect church grounds.',
    null,
    'Wide + tripod for night sky; dress for alpine cold.',
    '35–85mm with church/lake backdrop — keep paths clear.',
    '{"landscape":{"aperture":"f/2.8–f/4 (night) / f/8–f/11 (day)","iso":"1600–6400 (night) / 100–200 (day)","shutter":"10–25s (night) / 1/60–1/125 (day)","filter":null},"portrait":{"aperture":"f/2.8–f/5.6","iso":"200–1600","shutter":"1/160+","filter":null}}'::jsonb,
    'Red/low light only at night; never block doorways during services. Trip: NZ-6D5N.',
    'ใช้ไฟแดง/ไฟอ่อนตอนกลางคืน อย่าขวางทางเข้าโบสถ์ ทริป: NZ-6D5N',
    'Cold wind off the lake. Dark-sky etiquette — no bright white lights. [REVIEW: confirm any local access notices.]',
    'หนาวลมแรงจากทะเลสาบ ไม่ใช้ไฟขาวแรง [REVIEW: ป้ายเข้าถึงท้องถิ่น]',
    'restricted',
    'Follow CAA NZ rules; avoid flying over people near the church.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.9,
    50,
    true,
    'Merged curated #13 Lake Tekapo.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111202'::uuid,
    'aoraki-hooker-valley',
    'Aoraki / Mount Cook — Hooker Valley',
    'ออรากิ / เมาท์คุก — หุบเขาฮุคเกอร์',
    'Aoraki/Mount Cook National Park, Canterbury, NZ',
    'อุทยานแห่งชาติออรากิ/เมาท์คุก, แคนเทอร์เบอรี, นิวซีแลนด์',
    -43.7187, 170.09315,
    'https://maps.google.com/?q=Hooker+Valley+Track,+Aoraki+Mount+Cook',
    'DOC Hooker Valley Track with classic valley views toward Aoraki/Mount Cook — signature South Island alpine landscape.',
    'เส้นทาง Hooker Valley ของ DOC มองเห็นหุบเขาและยอดออรากิ/เมาท์คุก',
    array['Landscape','Nature','Sunrise','Portrait'],
    'Golden hour / clear alpine light on the peaks',
    'Shoulder seasons often clearer; check DOC alerts year-round',
    '~3.5–4 hrs from Queenstown / via Twizel from Christchurch',
    'White Horse Hill car park (DOC). Follow marked track and bridges.',
    null,
    'Wide to standard zoom + alpine layers.',
    'People-with-mountain frames — stay on marked track.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/60–1/250","filter":"CPL optional"},"portrait":{"aperture":"f/2.8–f/5.6","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Check DOC Hooker Valley Track status before going. Trip: NZ-6D5N / NZ-10D9N.',
    'เช็คสถานะเส้นทาง DOC ก่อนไป ทริป: NZ-6D5N / NZ-10D9N',
    'Alpine weather, glacial rivers, sudden cloud/wind. Stay on marked track. [REVIEW: GPS = White Horse Hill trailhead.]',
    'อากาศอัลไพน์ แม่น้ำธารน้ำแข็ง — เดินตามทาง DOC [REVIEW: พิกัดจุดจอด]',
    'restricted',
    'DOC national park — permits usually required.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.9,
    55,
    true,
    'Merged curated #12 Aoraki / Mount Cook.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111203'::uuid,
    'lake-pukaki-peters-lookout',
    'Lake Pukaki — Peter''s Lookout',
    'ทะเลสาบพูคากิ — จุดชมวิว Peter’s Lookout',
    'Mount Cook Road (SH80), near Lake Pukaki, NZ',
    'ถนน Mount Cook (SH80) ใกล้ทะเลสาบพูคากิ, นิวซีแลนด์',
    -44.19, 170.14,
    'https://maps.google.com/?q=Peters+Lookout,+Lake+Pukaki',
    'Roadside lookout on SH80 with turquoise Lake Pukaki and Aoraki/Mount Cook views — classic Mackenzie Country stop (covers curated Lake Pukaki + Peter’s Lookout).',
    'จุดชมวิวข้างทาง SH80 มองทะเลสาบพูคากิสีเขียวฟ้าและยอดออรากิ — จุดคลาสสิก Mackenzie (รวม Lake Pukaki + Peter’s Lookout)',
    array['Landscape','Sunrise','Sunset','Nature'],
    'Sunrise / clear mountain days',
    'Year-round; clearest after cold fronts (verify)',
    '~2.5–3 hrs from Queenstown / on SH80 toward Mount Cook',
    'Signed roadside pull-off on SH80. Park fully off the lane.',
    null,
    'Wide–mid zoom; polariser can deepen lake colour.',
    'People with lake/mountain backdrop — keep clear of traffic.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/250","filter":"CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'SH80 is busy — park fully off the lane. Trip: NZ-6D5N.',
    'SH80 รถเยอะ — จอดให้พ้นเลน ทริป: NZ-6D5N',
    'High-speed tourist road. Strong wind possible. [REVIEW: exact pull-off pin vs alternate SH80 bays.]',
    'ถนนเร็ว ลมแรงได้ [REVIEW: พิกัดจุดจอด]',
    'restricted',
    'Follow CAA NZ; avoid flying near traffic or people.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.8,
    60,
    false,
    'Merged curated #16 Lake Pukaki + #19 Peter’s Lookout into one row.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111204'::uuid,
    'that-wanaka-tree',
    'Wānaka — That Wānaka Tree',
    'วานากา — ต้นไม้ That Wānaka Tree',
    'Lake Wānaka, Otago, NZ',
    'ทะเลสาบวานากา, โอทาโก, นิวซีแลนด์',
    -44.698, 169.118,
    'https://maps.google.com/?q=That+Wanaka+Tree',
    'The famous solitary willow in Lake Wānaka — Wānaka’s most photographed lakeside landmark (curated Wanaka entry).',
    'ต้นหลิวโดดเดี่ยวในทะเลสาบวานากา — จุดแลนด์มาร์คริมทะเลสาบที่ถ่ายมากที่สุดของวานากา',
    array['Landscape','Portrait','Sunrise','Sunset'],
    'Sunrise / calm water reflections',
    'Year-round; calm mornings best for reflections',
    '~1 hr from Queenstown',
    'Roadside parking near the tree precinct; short walk to shoreline.',
    null,
    'Wide lens; ND for long exposure water when safe.',
    'People with tree/lake — share the viewpoint; do not climb the tree.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND / CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Share the viewpoint; do not climb or damage the tree. Trip: NZ-6D5N.',
    'แชร์มุมถ่าย อย่าปีน/ทำลายต้นไม้ ทริป: NZ-6D5N',
    'Cold water and slippery rocks at the shoreline. [REVIEW: peak-crowd etiquette / any new barriers.]',
    'น้ำเย็น หินลื่นริมตลิ่ง [REVIEW: ฝูงชน/แนวกั้นใหม่]',
    'restricted',
    'Follow CAA NZ; avoid flying over people at the viewpoint.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.8,
    65,
    true,
    'Merged curated #14 Wanaka into That Wānaka Tree row.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111301'::uuid,
    'great-ocean-road',
    'Great Ocean Road',
    'เกรทโอเชียนโรด',
    'Great Ocean Road, Victoria',
    'เกรทโอเชียนโรด, วิกตอเรีย',
    -38.668, 143.87,
    'https://maps.google.com/?q=Great+Ocean+Road,+Victoria',
    'Coastal highway and lookouts between Torquay and the Shipwreck Coast — classic Victoria seascape itinerary (pin near Apollo Bay / mid-route).',
    'ชายฝั่งและจุดชมวิวระหว่าง Torquay ถึง Shipwreck Coast — ทริปทะเลวิกตอเรียคลาสสิก',
    array['Landscape','Coastal','Sunrise','Sunset'],
    'Golden hour at cliff lookouts',
    'Year-round; winter swell dramatic (verify weather)',
    '~2–4 hrs from Melbourne depending on stop',
    'Signed lookouts along the Great Ocean Road; use marked car parks only.',
    null,
    'Wide lens + ND for long exposures when safe.',
    'People against ocean cliffs — stay behind barriers.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND / CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Build time for stops — do not rush cliff edges. Trip: MEL-4D3N.',
    'เผื่อเวลาแวะจุดชมวิว — อย่ารีบที่ขอบหน้าผา ทริป: MEL-4D3N',
    'Unfenced cliffs and strong wind. [REVIEW: choose a primary hero lookout pin if this corridor is too broad.]',
    'หน้าผาไม่มีรั้ว ลมแรง [REVIEW: เลือกจุดหลักถ้าช่วงทางกว้างเกินไป]',
    'restricted',
    'Follow CASA; many lookouts are crowded — avoid flying over people.',
    'MEL-4D3N',
    'MEL-4D3N',
    4.8,
    110,
    true,
    'Corridor pin near Apollo Bay — Saen may prefer a specific lookout.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111302'::uuid,
    'twelve-apostles',
    'The Twelve Apostles',
    'สิบสองอัครสาวก (Twelve Apostles)',
    'Port Campbell National Park, Victoria',
    'อุทยานแห่งชาติพอร์ตแคมป์เบลล์, วิกตอเรีย',
    -38.6657, 143.105,
    'https://maps.google.com/?q=Twelve+Apostles,+Victoria',
    'Limestone stacks along the Shipwreck Coast — Victoria’s most famous Great Ocean Road seascape.',
    'เสาหินปูนริมชายฝั่ง Shipwreck Coast — วิวทะเลที่โด่งดังที่สุดของเกรทโอเชียนโรด',
    array['Landscape','Coastal','Sunrise','Sunset'],
    'Sunrise / sunset from viewing platforms',
    'Year-round; clear winter mornings often dramatic',
    '~3.5–4.5 hrs from Melbourne',
    'Official visitor precinct / boardwalk platforms. Stay behind barriers.',
    null,
    'Wide–mid zoom; ND for long exposure seascapes.',
    'Portrait against stacks from platforms only.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND / CPL"},"portrait":{"aperture":"f/2.8–f/5.6","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Arrive early for parking in peak season. Trip: MEL-4D3N.',
    'มาถึงก่อนเพื่อจอดรถช่วงพีค ทริป: MEL-4D3N',
    'Unstable cliff edges — stay on boardwalks. Strong wind and spray. [REVIEW: current boardwalk closure notices.]',
    'หน้าผาทรุดได้ — อยู่บนทางเดิน ลมแรงและละอองน้ำ [REVIEW: ปิดทางเดินชั่วคราว]',
    'restricted',
    'National park / crowded precinct — check Parks Victoria / CASA rules.',
    'MEL-4D3N',
    'MEL-4D3N',
    4.9,
    115,
    true,
    'Confirm Parks Victoria drone rules for this precinct.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111303'::uuid,
    'pink-lake-victoria',
    'Pink Lake (Victoria)',
    'ทะเลสาบสีชมพู (วิกตอเรีย)',
    'Dimboola / Little Desert region, Victoria',
    'ย่าน Dimboola / Little Desert, วิกตอเรีย',
    -36.405, 141.96,
    'https://maps.google.com/?q=Pink+Lake,+Dimboola+Victoria',
    'Seasonal pink algae/salt-lake colour near Dimboola — intensity varies with water level and season.',
    'ทะเลสาบเค็มสีชมพูตามฤดูกาลใกล้ Dimboola — ความเข้มของสีขึ้นกับระดับน้ำและฤดู',
    array['Landscape','Nature','Portrait'],
    'Midday–afternoon when colour is strongest (verify season)',
    'Colour is seasonal — often stronger in warmer months [REVIEW]',
    '~3.5–4 hrs from Melbourne',
    'Roadside / park access near Dimboola Pink Lake — stay on public tracks.',
    null,
    'Wide–mid; polariser can help saturate colour.',
    'People with pink water backdrop — soft afternoon light.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/250","filter":"CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Colour is not guaranteed every visit. Trip: MEL-4D3N (western VIC detour — confirm itinerary).',
    'สีชมพูไม่การันตีทุกครั้ง ทริป: MEL-4D3N (อาจเป็นทางแยก — ยืนยันทริป)',
    'Soft lake edges can be muddy. [REVIEW: exact public access pin + whether MEL trip includes this stop.]',
    'ขอบทะเลสาบเละได้ [REVIEW: พิกัดเข้าถึงสาธารณะ และการรวมในทริป MEL]',
    'restricted',
    'Follow CASA; avoid disturbing wildlife.',
    'MEL-4D3N',
    'MEL-4D3N',
    4.6,
    120,
    false,
    'Pink intensity highly seasonal; confirm access pin and trip relevance.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111304'::uuid,
    'melbourne-city-landmarks',
    'Melbourne City Landmarks',
    'แลนด์มาร์คใจกลางเมลเบิร์น',
    'Melbourne CBD, Victoria',
    'เมลเบิร์น CBD, วิกตอเรีย',
    -37.8175, 144.9675,
    'https://maps.google.com/?q=Flinders+Street+Station,+Melbourne',
    'Cluster pin for State Library Victoria, Princes Bridge, and Flinders Street Station — classic Melbourne urban architecture frames.',
    'จุดรวม State Library Victoria, Princes Bridge และสถานี Flinders Street — สถาปัตยกรรมเมืองเมลเบิร์นคลาสสิก',
    array['Portrait','Landscape','Night'],
    'Blue hour / soft overcast for buildings; night for lights',
    'Year-round',
    'Melbourne CBD (0 — city centre)',
    'Use public transport or paid CBD parking; walk between landmarks.',
    'Tram / Metro to Flinders Street or State Library stops.',
    'Wide–standard zoom; tripod for night (check tripod rules indoors).',
    '35–85mm for people with station/bridge backdrop.',
    '{"landscape":{"aperture":"f/8–f/11 (day) / f/4–f/8 (night)","iso":"100–400 (day) / 400–1600 (night)","shutter":"1/60–1/200 (day) / 1–8s (night)","filter":null},"portrait":{"aperture":"f/2–f/4","iso":"100–800","shutter":"1/160+","filter":null}}'::jsonb,
    'State Library interior may have photography rules — check on the day. Trip: MEL-4D3N.',
    'ภายใน State Library อาจมีกฎถ่ายภาพ — เช็ควันนั้น ทริป: MEL-4D3N',
    'Busy traffic at Princes Bridge / Flinders St. [REVIEW: indoor photo policy at State Library Victoria.]',
    'การจราจรหนาแน่นที่สะพาน/สถานี [REVIEW: นโยบายถ่ายภาพใน State Library]',
    'prohibited',
    'CBD / crowded public spaces — do not fly without approvals.',
    'MEL-4D3N',
    'MEL-4D3N',
    4.7,
    125,
    false,
    'Cluster pin at Flinders St — may split into 3 spots later.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111305'::uuid,
    'field-of-light-uluru',
    'Field of Light (Uluru)',
    'Field of Light ที่อูลูรู',
    'Near Yulara / Uluru, NT',
    'ใกล้ Yulara / อูลูรู, นอร์เทิร์นเทร์ริทอรี',
    -25.2408, 130.982,
    'https://maps.google.com/?q=Field+of+Light,+Uluru',
    'Bruce Munro’s Field of Light installation near Uluru — ticketed night experience with desert light art and Uluru views (operator access only).',
    'งานติดตั้ง Field of Light ของ Bruce Munro ใกล้ อูลูรู — ประสบการณ์กลางคืนแบบมีตั๋ว (เข้าได้ผ่านผู้จัดเท่านั้น)',
    array['Night','Portrait','Landscape'],
    'After dark (ticketed sessions)',
    'Year-round evenings; book ahead in peak season',
    'Flight to AYQ + resort transfer',
    'Tour/operator transfer only — not a free public walk-in site.',
    null,
    'Fast wide lens; high ISO; check operator camera rules.',
    'People with light field — follow guide instructions.',
    '{"landscape":{"aperture":"f/2.8–f/4","iso":"1600–6400","shutter":"1–8s","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"800–3200","shutter":"1/60–1/125","filter":null}}'::jsonb,
    'Book official Field of Light tickets. Trip: ULU-4D3N. [REVIEW: whether current Trip2Talk Uluru itinerary includes this.]',
    'จองตั๋ว Field of Light อย่างเป็นทางการ ทริป: ULU-4D3N [REVIEW: ทริปปัจจุบันรวมจุดนี้หรือไม่]',
    'Ticketed private experience — follow staff directions. Desert night cold. [REVIEW: exact operator pin / photography restrictions.]',
    'เข้าได้เฉพาะผู้มีตั๋ว ตามคำแนะนำสตาฟ กลางคืนทะเลทรายหนาว [REVIEW: พิกัด/ข้อห้ามถ่าย]',
    'prohibited',
    'Not permitted at this ticketed site / park vicinity without authorisation.',
    'ULU-4D3N',
    'ULU-4D3N',
    4.8,
    32,
    true,
    'Confirm itinerary inclusion and operator photo rules.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111306'::uuid,
    'kata-tjuta-dune',
    'Kata Tjuta (The Olgas) — Dune Viewing',
    'กาตาจูตา (The Olgas) — จุดชมวิวเนินทราย',
    'Uluru-Kata Tjuta National Park, NT',
    'อุทยานแห่งชาติอูลูรู-กาตาจูตา, นอร์เทิร์นเทร์ริทอรี',
    -25.3, 130.909,
    'https://maps.google.com/?q=Kata+Tjuta+Dune+Viewing+Area',
    'Designated dune viewing area for Kata Tjuta (The Olgas) — sweeping desert light on domed rock formations on Aṉangu land.',
    'จุดชมวิวเนินทรายสำหรับกาตาจูตา — แสงทะเลทรายบนกลุ่มหินโดม บนดินแดนของชาว Aṉangu',
    array['Landscape','Portrait','Sunrise','Sunset'],
    'Sunrise / late afternoon',
    'Apr–Sep cooler; summer extreme heat',
    'Flight to AYQ + park roads',
    'Parks pass required. Use designated dune viewing car park and paths.',
    null,
    'Wide–mid zoom; dust protection.',
    'People with domes backdrop — stay on marked areas.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/125–1/250","filter":"CPL optional"},"portrait":{"aperture":"f/2.8–f/5.6","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Combine with Uluru sunrise/sunset on multi-day itineraries. Trip: ULU-4D3N.',
    'คู่กับจุดชมวิวอูลูรูในทริปหลายวัน ทริป: ULU-4D3N',
    'Parks pass required. Extreme heat. Cultural photography restrictions may apply in some areas — follow Parks Australia. [REVIEW: Walpa Gorge walk difficulty if promoting walks.]',
    'ต้องมีบัตรอุทยาน อากาศร้อนจัด บางพื้นที่มีข้อห้ามถ่ายภาพ [REVIEW: ความยากเส้นทาง Walpa Gorge]',
    'prohibited',
    'Drones not permitted in the national park without authorisation.',
    'ULU-4D3N',
    'ULU-4D3N',
    4.9,
    34,
    true,
    'Confirm dune viewing pin vs Walpa Gorge trailhead preference.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111307'::uuid,
    'uluru-camel-express',
    'Camel Express (Uluru)',
    'อูฐ Camel Express ที่อูลูรู',
    'Near Yulara, NT',
    'ใกล้ Yulara, นอร์เทิร์นเทร์ริทอรี',
    -25.2405, 130.988,
    'https://maps.google.com/?q=Uluru+Camel+Tours,+Yulara',
    'Ticketed camel-tour photo opportunity near Yulara with desert and Uluru backdrop — operator-led, not a free public lookout.',
    'โอกาสถ่ายภาพกับอูฐแบบมีตั๋วใกล้ Yulara พื้นหลังทะเลทราย/อูลูรู — ผ่านผู้จัดเท่านั้น',
    array['Portrait','Landscape','Sunrise','Sunset'],
    'Sunrise or sunset camel tours (booked)',
    'Apr–Sep more comfortable temperatures',
    'Flight to AYQ + resort area',
    'Tour operator pickup / booked experience only.',
    null,
    'Mid zoom for camel line + landscape.',
    'Fast portrait lens; dust and animal movement.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–400","shutter":"1/250+","filter":null},"portrait":{"aperture":"f/2–f/2.8","iso":"100–800","shutter":"1/320+","filter":null}}'::jsonb,
    'Book via official Uluru camel operators. Trip: ULU-4D3N. [REVIEW: whether Trip2Talk includes camel ride.]',
    'จองกับผู้ให้บริการอูฐอย่างเป็นทางการ ทริป: ULU-4D3N [REVIEW: ทริปมีขี่อูฐหรือไม่]',
    'Follow animal-handling instructions. Dust and heat. [REVIEW: operator name / exact meeting pin.]',
    'ทำตามคำแนะนำการดูแลสัตว์ ฝุ่นและความร้อน [REVIEW: ชื่อผู้จัด/จุดนัด]',
    'prohibited',
    'Not appropriate over animals/people without approvals.',
    'ULU-4D3N',
    'ULU-4D3N',
    4.6,
    36,
    false,
    'Confirm operator and itinerary inclusion.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111308'::uuid,
    'nugget-point-lighthouse',
    'Nugget Point Lighthouse',
    'ประภาคาร Nugget Point',
    'The Catlins, Otago, NZ',
    'The Catlins, โอทาโก, นิวซีแลนด์',
    -46.448, 169.814,
    'https://maps.google.com/?q=Nugget+Point+Lighthouse',
    'Clifftop lighthouse and sea stacks at Nugget Point — classic Catlins coastal landscape.',
    'ประภาคารบนหน้าผาและเสาหินทะเลที่ Nugget Point — วิวชายฝั่ง Catlins คลาสสิก',
    array['Landscape','Coastal','Sunrise','Portrait'],
    'Sunrise / clear coastal light',
    'Year-round; windy year-round',
    '~2 hrs from Dunedin / multi-day from Queenstown via Catlins',
    'DOC car park and walking track to lighthouse viewpoint.',
    null,
    'Wide lens; secure tripod in wind.',
    'People with lighthouse — stay behind fences.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/500","filter":"CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/250+","filter":null}}'::jsonb,
    'Strong wind is normal — secure gear. Trip: NZ-10D9N (Catlins often on longer itineraries). [REVIEW: NZ-6D5N may not include Catlins.]',
    'ลมแรงเกือบตลอด — ยึดขาตั้ง ทริป: NZ-10D9N [REVIEW: NZ-6D5N อาจไม่ผ่าน Catlins]',
    'Unfenced cliffs and extreme wind. [REVIEW: track condition / seal colony viewing etiquette.]',
    'หน้าผาไม่มีรั้ว ลมแรงจัด [REVIEW: สภาพทาง / การชมฝูงแมวน้ำ]',
    'restricted',
    'Follow CAA NZ; cliff edges and wildlife — fly with care or not at all.',
    'NZ-10D9N',
    'NZ-10D9N',
    4.8,
    70,
    false,
    'Confirm whether short NZ-6D5N trips reach Catlins; linked NZ-10D9N for now.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111309'::uuid,
    'queenstown',
    'Queenstown',
    'ควีนส์ทาวน์',
    'Queenstown, Otago, NZ',
    'ควีนส์ทาวน์, โอทาโก, นิวซีแลนด์',
    -45.0312, 168.6626,
    'https://maps.google.com/?q=Queenstown,+New+Zealand',
    'Lakeside alpine town on Lake Wakatipu with Remarkables backdrop — hub for South Island photo itineraries.',
    'เมืองริมทะเลสาบ Wakatipu กับฉากหลัง The Remarkables — ศูนย์กลางทริปถ่ายภาพเกาะใต้',
    array['Landscape','Portrait','Night','Sunrise'],
    'Golden hour on the lake foreshore / blue hour town lights',
    'Year-round; autumn colour strong (verify timing)',
    'Queenstown hub (0) — flights from AU major cities',
    'Town foreshore and public lookouts (e.g. near Queenstown Gardens / steamboat pier).',
    null,
    'Wide–mid for lake + mountains.',
    '35–85mm for people with Remarkables backdrop.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/60–1/200","filter":null},"portrait":{"aperture":"f/2–f/4","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Foreshore is busy at sunset — arrive early. Trip: NZ-6D5N / NZ-10D9N.',
    'ริมทะเลสาบแน่นตอนพระอาทิตย์ตก — มาถึงก่อน ทริป: NZ-6D5N / NZ-10D9N',
    'Cold lake wind. [REVIEW: pick a primary hero lookout (Bob’s Peak vs foreshore) if splitting later.]',
    'ลมเย็นจากทะเลสาบ [REVIEW: เลือกจุดหลักถ้าจะแยกภายหลัง]',
    'restricted',
    'Busy town / airport vicinity — check CAA NZ and local rules.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.8,
    72,
    true,
    'Town cluster pin — may split Bob’s Peak / Kelvin Heights later.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111310'::uuid,
    'moeraki-boulders',
    'Moeraki Boulders',
    'ก้อนหินโมเอรากิ (Moeraki Boulders)',
    'Moeraki, Otago, NZ',
    'โมเอรากิ, โอทาโก, นิวซีแลนด์',
    -45.345, 170.826,
    'https://maps.google.com/?q=Moeraki+Boulders',
    'Spherical concretions on Koekohe Beach — iconic Otago coastal sunrise/tide landscape.',
    'ก้อนหินทรงกลมบนหาด Koekohe — วิวชายฝั่งโอทาโกคลาสสิกตอนพระอาทิตย์ขึ้น/น้ำขึ้นน้ำลง',
    array['Landscape','Coastal','Sunrise','Portrait'],
    'Sunrise / low–mid tide for access around boulders',
    'Year-round; check tide tables',
    '~1–1.5 hrs from Dunedin / on coastal route from Christchurch',
    'Signed car park and beach access track.',
    null,
    'Wide lens; ND for long exposure water; watch tide.',
    'People with boulder shapes — keep clear of incoming swell.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND / CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Check tide before going onto wet sand. Trip: NZ-10D9N. [REVIEW: NZ-6D5N coverage.]',
    'เช็คน้ำขึ้นน้ำลงก่อนลงหาด ทริป: NZ-10D9N [REVIEW: NZ-6D5N ครอบคลุมหรือไม่]',
    'Incoming tide and slippery seaweed. Do not climb unstable stacks. [REVIEW: current access fees/parking.]',
    'น้ำขึ้นและสาหร่ายลื่น อย่าปีนก้อนหินไม่มั่นคง [REVIEW: ค่าจอด/เข้าถึง]',
    'restricted',
    'Crowded beach — avoid flying over people.',
    'NZ-10D9N',
    'NZ-10D9N',
    4.8,
    74,
    false,
    'Tide-dependent access; confirm trip code for shorter NZ tours.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111311'::uuid,
    'lindis-pass',
    'Lindis Pass',
    'ช่องเขา Lindis Pass',
    'Lindis Pass, Otago/Canterbury, NZ',
    'Lindis Pass, โอทาโก/แคนเทอร์เบอรี, นิวซีแลนด์',
    -44.64, 169.64,
    'https://maps.google.com/?q=Lindis+Pass,+New+Zealand',
    'High alpine pass on SH8 with golden tussock hills — classic Mackenzie/Otago road landscape.',
    'ช่องเขาสูงบน SH8 กับเนินหญ้าทอง — วิวถนน Mackenzie/Otago คลาสสิก',
    array['Landscape','Nature','Sunrise','Sunset'],
    'Golden hour on tussock slopes',
    'Autumn colour strong; winter ice possible on road',
    '~1.5–2 hrs from Queenstown toward Tekapo / Mount Cook corridor',
    'Signed roadside lookouts on SH8 — park fully off the highway.',
    null,
    'Wide–mid; polariser for sky/contrast.',
    'People with rolling hills — keep clear of traffic.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/250","filter":"CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Wind is strong at the pass. Trip: NZ-6D5N.',
    'ลมแรงที่ช่องเขา ทริป: NZ-6D5N',
    'High-speed highway. Ice/snow in winter. [REVIEW: preferred lookout bay pin.]',
    'ถนนเร็ว น้ำแข็ง/หิมะในฤดูหนาว [REVIEW: จุดจอดที่แนะนำ]',
    'restricted',
    'Highway corridor — avoid flying near traffic.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.7,
    76,
    false,
    'Exact lookout pull-off pin needs confirmation.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111312'::uuid,
    'mt-john-observatory',
    'Mt John Observatory',
    'หอดูดาว Mt John',
    'Lake Tekapo, Mackenzie District, NZ',
    'ทะเลสาบเทคาโป, เขตแมคเคนซี, นิวซีแลนด์',
    -43.9856, 170.4642,
    'https://maps.google.com/?q=University+of+Canterbury+Mt+John+Observatory',
    'Hilltop observatory above Lake Tekapo with panoramic Mackenzie Country views — day landscape + dark-sky night tours.',
    'หอดูดาวบนเนินเหนือทะเลสาบเทคาโป มองวิว Mackenzie — ทั้งกลางวันและทัวร์ท้องฟ้ามืด',
    array['Night','Milky Way','Landscape','Portrait'],
    'Clear nights (tours) / daytime panorama',
    'Year-round; winter nights often clearest',
    '~10–15 min drive up from Lake Tekapo township',
    'Road to summit; café/observatory precinct. Night access often via booked tours.',
    null,
    'Wide + tripod for night; layers for wind.',
    'People with lake/mountain backdrop by day.',
    '{"landscape":{"aperture":"f/2.8–f/4 (night) / f/8 (day)","iso":"1600–6400 (night) / 100–200 (day)","shutter":"10–25s (night) / 1/125 (day)","filter":null},"portrait":{"aperture":"f/2.8–f/5.6","iso":"200–1600","shutter":"1/160+","filter":null}}'::jsonb,
    'Book Earth & Sky / observatory tours for night access. Trip: NZ-6D5N.',
    'จองทัวร์กลางคืนกับผู้จัดท้องถิ่น ทริป: NZ-6D5N',
    'Cold wind at summit. Dark-sky etiquette. [REVIEW: current public vs tour-only night access.]',
    'ลมหนาวที่ยอดเนิน มารยาทท้องฟ้ามืด [REVIEW: กลางคืนเข้าได้เองหรือต้องทัวร์]',
    'restricted',
    'Near observatory / dark-sky reserve — avoid interfering with astronomy.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.8,
    78,
    true,
    'Confirm night access rules and tour operator naming.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111313'::uuid,
    'irishman-creek-station',
    'Irishman Creek Station',
    'สถานี Irishman Creek',
    'Mackenzie District, NZ',
    'เขตแมคเคนซี, นิวซีแลนด์',
    -44.05, 170.25,
    'https://maps.google.com/?q=Irishman+Creek+Station,+New+Zealand',
    'Historic high-country station precinct in Mackenzie Country — landscape/heritage frames (access may be private or tour-only).',
    'สถานีไฮคันทรีประวัติศาสตร์ใน Mackenzie — วิวแลนด์สเคป/มรดก (การเข้าถึงอาจเป็นพื้นที่ส่วนตัวหรือทัวร์)',
    array['Landscape','Portrait','Nature'],
    'Golden hour on tussock country',
    'Year-round; verify access',
    '~20–40 min from Lake Tekapo / Twizel corridor [REVIEW]',
    '[REVIEW: public roadside views vs private station access — do not enter private land without permission.]',
    null,
    'Mid–tele for rolling hills.',
    'Heritage/people frames only where public access allows.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/250","filter":null},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Do not enter private station land without permission. Trip: NZ-6D5N. [REVIEW: exact public pin.]',
    'อย่าเข้าพื้นที่สถานีส่วนตัวโดยไม่ได้รับอนุญาต ทริป: NZ-6D5N [REVIEW: พิกัดสาธารณะ]',
    'Private property risk. [REVIEW: confirm whether Trip2Talk stops here or roadside only.]',
    'อาจเป็นที่ดินส่วนตัว [REVIEW: ทริปแวะหรือถ่ายจากข้างทางเท่านั้น]',
    'restricted',
    'Private land — never fly without landowner permission.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.5,
    80,
    false,
    'HIGH PRIORITY REVIEW — access/private land; pin is approximate Mackenzie corridor.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111314'::uuid,
    'milford-sound',
    'Milford Sound / Piopiotahi',
    'มิลฟอร์ดซาวด์ / Piopiotahi',
    'Fiordland National Park, NZ',
    'อุทยานแห่งชาติฟยอร์ดแลนด์, นิวซีแลนด์',
    -44.671, 167.925,
    'https://maps.google.com/?q=Milford+Sound,+New+Zealand',
    'Fiordland’s iconic fiord with Mitre Peak — cruise or lookout frames in a high-rainfall UNESCO park.',
    'ฟยอร์ดสัญลักษณ์ของฟยอร์ดแลนด์กับ Mitre Peak — จากเรือหรือจุดชมวิวในอุทยานยูเนสโก',
    array['Landscape','Nature','Portrait','Coastal'],
    'Any clear break in weather; waterfalls strongest after rain',
    'Year-round; expect rain frequently',
    '~4 hrs from Queenstown (full day) — often cruise-based',
    'Milford Road to terminal; many photos from cruise boats. Check DOC road status.',
    null,
    'Weather-sealed wide lens; rain cover essential.',
    'People on deck with peaks — watch spray.',
    '{"landscape":{"aperture":"f/5.6–f/11","iso":"100–400","shutter":"1/125–1/500","filter":null},"portrait":{"aperture":"f/2.8–f/4","iso":"100–800","shutter":"1/250+","filter":null}}'::jsonb,
    'Book cruises early in peak season. Trip: NZ-6D5N / NZ-10D9N.',
    'จองเรือล่วงหน้าช่วงพีค ทริป: NZ-6D5N / NZ-10D9N',
    'Avalanche risk on Milford Road in winter/spring — check NZTA/DOC. [REVIEW: day-trip vs overnight itinerary.]',
    'ถนนมิลฟอร์ดมีความเสี่ยงหิมะถล่มฤดูหนาว/ฤดูใบไม้ผลิ — เช็ค NZTA/DOC [REVIEW: ทริปวันเดียวหรือค้าง]',
    'restricted',
    'National park — authorisation typically required.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.9,
    82,
    true,
    'Confirm whether all NZ-6D5N departures include Milford.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111315'::uuid,
    'arrowtown',
    'Arrowtown',
    'แอร์โรว์ทาวน์',
    'Arrowtown, Otago, NZ',
    'แอร์โรว์ทาวน์, โอทาโก, นิวซีแลนด์',
    -44.9405, 168.8335,
    'https://maps.google.com/?q=Arrowtown,+New+Zealand',
    'Historic gold-rush village with autumn avenue trees and Arrow River — classic Central Otago townscapes.',
    'หมู่บ้านยุคทองคำเก่ากับต้นไม้สีใบไม้ร่วงและแม่น้ำ Arrow — วิวเมือง Central Otago คลาสสิก',
    array['Portrait','Landscape','Nature'],
    'Autumn colour / soft morning light on Buckingham Street',
    'Peak autumn colour usually Apr–May [REVIEW exact week]',
    '~20–30 min from Queenstown',
    'Town parking; walk Buckingham Street and river trails.',
    null,
    'Standard zoom for street + hills.',
    '35–85mm for people under autumn trees.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–400","shutter":"1/125–1/250","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Autumn weekends are crowded — arrive early. Trip: NZ-6D5N.',
    'สุดสัปดาห์ฤดูใบไม้ร่วงคนเยอะ — มาถึงก่อน ทริป: NZ-6D5N',
    'Slippery leaves on paths after rain. [REVIEW: Chinese Settlement photo etiquette/signage.]',
    'ใบไม้เปียกลื่นหลังฝน [REVIEW: มารยาทถ่ายที่ Chinese Settlement]',
    'restricted',
    'Busy village — avoid flying over people.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.7,
    84,
    false,
    'Confirm peak autumn colour window for marketing copy.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111316'::uuid,
    'fox-glacier',
    'Fox Glacier / Te Moeka o Tuawe',
    'ธารน้ำแข็งฟอกซ์ (Fox Glacier)',
    'West Coast, South Island, NZ',
    'เวสต์โคสต์, เกาะใต้, นิวซีแลนด์',
    -43.465, 170.017,
    'https://maps.google.com/?q=Fox+Glacier,+New+Zealand',
    'West Coast glacier valley viewpoints — ice, rainforest, and fast-changing weather (guided access onto ice).',
    'จุดชมธารน้ำแข็งฝั่งเวสต์โคสต์ — น้ำแข็ง ป่าฝน และอากาศเปลี่ยนไว (ขึ้นน้ำแข็งต้องมีไกด์)',
    array['Landscape','Nature'],
    'Daytime clear breaks',
    'Year-round; road/track status changes often',
    '~4–5 hrs from Queenstown via Haast (full day+)',
    'DOC car parks and valley tracks — follow closure signs. Glacier surface via guided tours only.',
    null,
    'Weather-sealed kit; rain cover.',
    'Limited — valley viewpoints.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/125–1/500","filter":null},"portrait":{"aperture":"f/2.8–f/5.6","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Check DOC track alerts daily. Trip: NZ-10D9N. [REVIEW: NZ-6D5N may skip West Coast.]',
    'เช็คประกาศ DOC ทุกวัน ทริป: NZ-10D9N [REVIEW: NZ-6D5N อาจไม่ขึ้นเวสต์โคสต์]',
    'Rockfall and changing ice — never cross barriers. [REVIEW: current valley walk length.]',
    'หินร่วงและน้ำแข็งเปลี่ยน — อย่าข้ามแนวกั้น [REVIEW: ความยาวทางเดินปัจจุบัน]',
    'restricted',
    'DOC land — authorisation typically required.',
    'NZ-10D9N',
    'NZ-10D9N',
    4.7,
    86,
    false,
    'Confirm which NZ packages include Fox Glacier.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111317'::uuid,
    'te-anau',
    'Te Anau',
    'เตอานัว (Te Anau)',
    'Te Anau, Fiordland, NZ',
    'เตอานัว, ฟยอร์ดแลนด์, นิวซีแลนด์',
    -45.414, 167.718,
    'https://maps.google.com/?q=Te+Anau,+New+Zealand',
    'Lakeside gateway town to Fiordland — calm Lake Te Anau foreshore and dusk mountain light.',
    'เมืองประตูสู่ฟยอร์ดแลนด์ริมทะเลสาบ — วิวริมน้ำและแสงยามเย็นบนภูเขา',
    array['Landscape','Portrait','Sunset','Night'],
    'Sunset on the foreshore / clear nights',
    'Year-round',
    '~2 hrs from Queenstown (common overnight before Milford)',
    'Town lakefront parks and walkways.',
    null,
    'Wide–mid for lake reflections.',
    'People with lake/mountain backdrop.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/60–1/200","filter":null},"portrait":{"aperture":"f/2–f/4","iso":"100–800","shutter":"1/160+","filter":null}}'::jsonb,
    'Good base night before Milford Sound. Trip: NZ-6D5N / NZ-10D9N.',
    'เหมาะค้างคืนก่อนมิลฟอร์ด ทริป: NZ-6D5N / NZ-10D9N',
    'Sandflies can be intense — cover up. [REVIEW: glow-worm caves as separate spot later.]',
    'ริ้นน้ำเค็มเยอะ — ใส่เสื้อแขนยาว [REVIEW: ถ้ำหนอนเรืองแสงแยกจุดภายหลัง]',
    'restricted',
    'Follow CAA NZ around town and lake.',
    'NZ-6D5N',
    'NZ-6D5N',
    4.6,
    88,
    false,
    'Optional future split: Te Anau glowworm caves.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111318'::uuid,
    'mount-wellington-kunanyi',
    'Mount Wellington (kunanyi)',
    'ภูเขาเวลลิงตัน (kunanyi)',
    'Hobart, Tasmania',
    'โฮบาร์ต, แทสเมเนีย',
    -42.896, 147.237,
    'https://maps.google.com/?q=kunanyi+Mount+Wellington+summit',
    'Hobart’s landmark mountain with summit boardwalk views over the city and Derwent — often windy and cloud-capped.',
    'ภูเขาสัญลักษณ์โฮบาร์ต มองเมืองและแม่น้ำ Derwent จากทางเดินยอดเขา — ลมแรงและมีเมฆปกคลุมบ่อย',
    array['Landscape','Portrait','Sunrise','Sunset'],
    'Clear summit windows (cloud lifts fast)',
    'Year-round; winter ice on road possible',
    '~30–40 min from Hobart CBD',
    'Pinnacle Road to summit (closures for ice/wind). Check council/road status.',
    null,
    'Wide lens; layers and gloves essential.',
    'People at boardwalk with city backdrop.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–400","shutter":"1/125–1/500","filter":null},"portrait":{"aperture":"f/2.8–f/4","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Check road open status before driving up. Trip: TAS-LH-4D3N / TAS-SU-4D3N / TAS-3D2N.',
    'เช็คถนนเปิดก่อนขึ้นเขา ทริป: TAS-LH-4D3N / TAS-SU-4D3N / TAS-3D2N',
    'Extreme wind and sudden cloud. Ice in winter. [REVIEW: preferred related_trip_code among TAS packages.]',
    'ลมแรงจัด เมฆขึ้นเร็ว น้ำแข็งในฤดูหนาว [REVIEW: เลือกรหัสทริป TAS ที่เหมาะสม]',
    'restricted',
    'Follow CASA; summit often crowded/windy — flying often impractical.',
    'TAS-LH-4D3N',
    'TAS-LH-4D3N',
    4.8,
    90,
    true,
    'Confirm primary TAS trip code for Hobart legs.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111319'::uuid,
    'bruny-island-neck',
    'Bruny Island — The Neck & Lighthouse',
    'เกาะบรูนี — The Neck และประภาคาร',
    'Bruny Island, Tasmania',
    'เกาะบรูนี, แทสเมเนีย',
    -43.27, 147.35,
    'https://maps.google.com/?q=The+Neck,+Bruny+Island',
    'Isthmus lookout (The Neck) and Bruny Island Lighthouse options — classic Hobart day-trip coastal frames.',
    'จุดชมวิวคอคอด The Neck และประภาคารเกาะบรูนี — วิวชายฝั่งทริปวันเดียวจากโฮบาร์ต',
    array['Landscape','Coastal','Portrait','Sunrise'],
    'Soft morning / late light at The Neck boardwalk',
    'Year-round; ferry timetable dependent',
    '~1.5–2.5 hrs from Hobart including ferry',
    'Ferry from Kettering; boardwalk at The Neck. Lighthouse is a separate drive south — allow time.',
    null,
    'Wide for isthmus; mid for lighthouse.',
    'People on Neck stairs/boardwalk — windy.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/250","filter":"CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Book ferry return with buffer. Trip: TAS-LH-4D3N. [REVIEW: lighthouse vs Neck as primary pin.]',
    'จองเรือขากลับเผื่อเวลา ทริป: TAS-LH-4D3N [REVIEW: จุดหลักประภาคารหรือ The Neck]',
    'Steep stairs at The Neck; strong wind. Wildlife on roads at dusk. [REVIEW: penguin viewing rules if promoting night.]',
    'บันไดชันที่ The Neck ลมแรง สัตว์ข้ามถนนตอนเย็น [REVIEW: กฎชมเพนกวินถ้าโปรโมตกลางคืน]',
    'restricted',
    'Wildlife-sensitive areas — fly carefully or not at all.',
    'TAS-LH-4D3N',
    'TAS-LH-4D3N',
    4.8,
    92,
    true,
    'Cluster pin at The Neck — lighthouse is a long extra drive.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111320'::uuid,
    'mona-hobart',
    'MONA (Museum of Old and New Art)',
    'พิพิธภัณฑ์ MONA โฮบาร์ต',
    'Berriedale, Hobart, Tasmania',
    'Berriedale, โฮบาร์ต, แทสเมเนีย',
    -42.8127, 147.258,
    'https://maps.google.com/?q=MONA,+Hobart',
    'World-famous museum architecture and river approach — exterior/grounds photo opportunity (interior rules apply).',
    'สถาปัตยกรรมพิพิธภัณฑ์ระดับโลกและทางเข้าฝั่งแม่น้ำ — เหมาะถ่ายภายนอก/ลาน (ภายในมีกฎ)',
    array['Portrait','Landscape','Night'],
    'Daytime exterior / ferry approach light',
    'Year-round; check opening days',
    '~15–20 min from Hobart CBD (or MONA ferry)',
    'Ticketed museum — ferry or road access. Follow MONA photography policy indoors.',
    'MONA ferry from Hobart waterfront.',
    'Wide for architecture exteriors.',
    'People with museum/river backdrop outdoors.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–400","shutter":"1/125–1/250","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–800","shutter":"1/160+","filter":null}}'::jsonb,
    'Confirm indoor photo rules on arrival. Trip: TAS-LH-4D3N / TAS-SU-4D3N.',
    'ยืนยันกฎถ่ายภาพภายในตอนถึง ทริป: TAS-LH-4D3N / TAS-SU-4D3N',
    'Some artworks prohibit photography. [REVIEW: current MONA photo policy.]',
    'บางงานศิลปะห้ามถ่าย [REVIEW: นโยบายถ่ายภาพ MONA ปัจจุบัน]',
    'prohibited',
    'Do not fly over museum precinct without approval.',
    'TAS-LH-4D3N',
    'TAS-LH-4D3N',
    4.7,
    94,
    false,
    'Interior photo policy must be verified before staff tips go live as advice.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111321'::uuid,
    'hobart-waterfront',
    'Hobart Waterfront & Market',
    'ริมน้ำโฮบาร์ตและตลาด',
    'Hobart, Tasmania',
    'โฮบาร์ต, แทสเมเนีย',
    -42.8826, 147.3307,
    'https://maps.google.com/?q=Constitution+Dock,+Hobart',
    'Constitution Dock / Salamanca area — harbour boats, mountain backdrop, and Salamanca Market energy (Saturdays).',
    'ย่าน Constitution Dock / Salamanca — เรือในอ่าว ฉากหลังภูเขา และบรรยากาศตลาด Salamanca (วันเสาร์)',
    array['Portrait','Landscape','Night'],
    'Blue hour harbour lights; Saturday market morning',
    'Year-round',
    'Hobart CBD waterfront (0)',
    'Public waterfront walkways; paid parking nearby.',
    'Central Hobart walking distance.',
    'Wide for docks + kunanyi backdrop.',
    '35–85mm for market/street portraits (ask before close-ups of people).',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–400","shutter":"1/125–1/250","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Salamanca Market is Saturdays — arrive early. Trip: TAS-LH-4D3N.',
    'ตลาด Salamanca เปิดวันเสาร์ — มาถึงก่อน ทริป: TAS-LH-4D3N',
    'Busy vehicle/pedestrian mix on market days. [REVIEW: drone near docks — generally avoid.]',
    'คนและรถหนาแน่นวันตลาด [REVIEW: โดรนใกล้ท่าเรือ — โดยทั่วไปหลีกเลี่ยง]',
    'prohibited',
    'Crowded urban waterfront — do not fly.',
    'TAS-LH-4D3N',
    'TAS-LH-4D3N',
    4.7,
    96,
    false,
    'Market day timing is Saturday-only.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111322'::uuid,
    'port-arthur-historic-site',
    'Port Arthur Historic Site',
    'แหล่งประวัติศาสตร์พอร์ตอาร์เธอร์',
    'Port Arthur, Tasmania',
    'พอร์ตอาร์เธอร์, แทสเมเนีย',
    -43.137, 147.846,
    'https://maps.google.com/?q=Port+Arthur+Historic+Site',
    'UNESCO-listed convict settlement ruins on the Tasman Peninsula — atmospheric heritage landscape (ticketed).',
    'แหล่งอาณานิคทัณฑ์ในบัญชียูเนสโกบนคาบสมุทรแทสมัน — วิวมรดกบรรยากาศ (ต้องมีตั๋ว)',
    array['Landscape','Portrait','Sunset'],
    'Soft afternoon light on ruins / dusk tours',
    'Year-round; check opening hours',
    '~1.5 hrs from Hobart',
    'Ticketed site — follow marked paths and site rules.',
    null,
    'Wide–mid for ruins and harbour.',
    'Respectful portraiture — avoid disrupting tours.',
    '{"landscape":{"aperture":"f/5.6–f/11","iso":"100–400","shutter":"1/60–1/200","filter":null},"portrait":{"aperture":"f/2–f/4","iso":"100–800","shutter":"1/160+","filter":null}}'::jsonb,
    'Allow half a day. Trip: TAS-LH-4D3N / TAS-SU-4D3N.',
    'เผื่อเวลาครึ่งวัน ทริป: TAS-LH-4D3N / TAS-SU-4D3N',
    'This is a place of difficult history — photograph respectfully. [REVIEW: commercial photo permit rules.]',
    'สถานที่มีประวัติศาสตร์หนัก — ถ่ายอย่างเคารพ [REVIEW: กฎถ่ายภาพเชิงพาณิชย์]',
    'prohibited',
    'Historic site — drones typically not allowed without permission.',
    'TAS-LH-4D3N',
    'TAS-LH-4D3N',
    4.8,
    98,
    true,
    'Confirm commercial photography rules for Trip2Talk use.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111323'::uuid,
    'bridestowe-lavender',
    'Bridestowe Lavender Estate',
    'ไร่ลาเวนเดอร์ Bridestowe',
    'Nabowla, Tasmania',
    'Nabowla, แทสเมเนีย',
    -41.2, 147.35,
    'https://maps.google.com/?q=Bridestowe+Lavender+Estate',
    'Famous lavender fields in northeast Tasmania — peak purple rows in summer flowering season (ticketed estate).',
    'ไร่ลาเวนเดอร์ชื่อดังทางตะวันออกเฉียงเหนือของแทสเมเนีย — แถวสีม่วงช่วงดอกบานฤดูร้อน (เข้าชมแบบมีตั๋ว)',
    array['Portrait','Landscape','Nature'],
    'Peak bloom days (typically Dec–Jan) [REVIEW exact window]',
    'Summer flowering only for classic purple fields',
    '~1 hr from Launceston',
    'Ticketed estate — follow visitor paths; do not crush plants.',
    null,
    'Wide for field rows; mid for detail.',
    'Classic lavender portrait — soft morning/evening light.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–200","shutter":"1/125–1/250","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Check bloom updates before travelling. Trip: TAS-3D2N. [REVIEW: whether itinerary includes Bridestowe.]',
    'เช็คช่วงดอกบานก่อนเดินทาง ทริป: TAS-3D2N [REVIEW: ทริปแวะหรือไม่]',
    'Stay on paths; bees in bloom season. [REVIEW: 2026/27 opening & bloom dates.]',
    'เดินตามทาง มีผึ้งช่วงดอกบาน [REVIEW: วันเปิดและช่วงดอกบาน]',
    'restricted',
    'Private estate — only with permission.',
    'TAS-3D2N',
    'TAS-3D2N',
    4.8,
    100,
    true,
    'Bloom window and itinerary inclusion need Saen confirmation.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111324'::uuid,
    'richmond-bridge',
    'Richmond Bridge',
    'สะพานริชมอนด์',
    'Richmond, Tasmania',
    'ริชมอนด์, แทสเมเนีย',
    -42.7335, 147.439,
    'https://maps.google.com/?q=Richmond+Bridge,+Tasmania',
    'Australia’s oldest stone bridge still in use — classic heritage reflection shots over the Coal River.',
    'สะพานหินที่เก่าแก่ที่สุดของออสเตรเลียที่ยังใช้งาน — วิวมรดกพร้อมเงาสะท้อนบนแม่น้ำ Coal',
    array['Landscape','Portrait','Sunrise'],
    'Soft morning light / calm reflections',
    'Year-round',
    '~25–30 min from Hobart',
    'Village parking; riverside public viewing areas.',
    null,
    'Wide for bridge + reflection; ND optional.',
    'People with bridge backdrop from riverbank.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–1/125","filter":"ND / CPL optional"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/160+","filter":null}}'::jsonb,
    'Combine with Hobart day itinerary. Trip: TAS-LH-4D3N.',
    'คู่กับทริปวันเดียวโฮบาร์ต ทริป: TAS-LH-4D3N',
    'Riverbank can be muddy. Watch traffic on bridge. [REVIEW: drone near heritage structure.]',
    'ตลิ่งเละได้ ระวังรถบนสะพาน [REVIEW: โดรนใกล้โครงสร้างมรดก]',
    'restricted',
    'Heritage precinct / people — fly only if legal and considerate.',
    'TAS-LH-4D3N',
    'TAS-LH-4D3N',
    4.7,
    102,
    false,
    'Straightforward heritage pin.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111325'::uuid,
    'cascade-brewery',
    'Cascade Brewery',
    'โรงเบียร์ Cascade',
    'South Hobart, Tasmania',
    'เซาท์โฮบาร์ต, แทสเมเนีย',
    -42.8945, 147.308,
    'https://maps.google.com/?q=Cascade+Brewery,+Hobart',
    'Historic brewery facade with kunanyi/Mt Wellington backdrop — classic Hobart architectural landscape.',
    'อาคารโรงเบียร์ประวัติศาสตร์กับฉากหลัง kunanyi/Mt Wellington — สถาปัตยกรรมโฮบาร์ตคลาสสิก',
    array['Landscape','Portrait'],
    'Soft morning / late light on the facade',
    'Year-round',
    '~10–15 min from Hobart CBD',
    'Public viewing from outside / visitor experiences may be ticketed — [REVIEW tour access].',
    null,
    'Standard zoom for building + mountain.',
    'People with brewery facade.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–200","shutter":"1/125–1/250","filter":null},"portrait":{"aperture":"f/2–f/2.8","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Exterior frames from public roadside/viewpoint. Trip: TAS-LH-4D3N.',
    'ถ่ายภายนอกจากจุดสาธารณะ ทริป: TAS-LH-4D3N',
    'Private property — do not enter restricted brewery areas. [REVIEW: visitor centre photo rules.]',
    'ที่ดินส่วนตัว — อย่าเข้าพื้นที่โรงงาน [REVIEW: กฎถ่ายที่ visitor centre]',
    'prohibited',
    'Private industrial site — no drones without permission.',
    'TAS-LH-4D3N',
    'TAS-LH-4D3N',
    4.5,
    104,
    false,
    'Confirm public exterior vantage and tour options.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111326'::uuid,
    'stanwell-tops-lookout',
    'Stanwell Tops Lookout',
    'จุดชมวิว Stanwell Tops',
    'Stanwell Tops, NSW',
    'Stanwell Tops, นิวเซาท์เวลส์',
    -34.226, 150.986,
    'https://maps.google.com/?q=Stanwell+Tops+Lookout',
    'Clifftop coastal lookout south of Sydney with hang-glider launch views along the Illawarra escarpment.',
    'จุดชมวิวหน้าผาชายฝั่งใต้ซิดนีย์ มองแนวหน้าผา Illawarra และจุดเครื่องร่อน',
    array['Landscape','Coastal','Portrait','Sunrise'],
    'Sunrise / clear morning',
    'Year-round',
    '~50–60 min from Sydney',
    'Signed lookout car park; stay behind barriers.',
    null,
    'Wide–mid for coastline.',
    'People with ocean/cliff backdrop — windy.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/500","filter":"CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/250+","filter":null}}'::jsonb,
    'Combine with Sea Cliff Bridge. Trip: KIA-1DAY / SYD-1DAY.',
    'คู่กับ Sea Cliff Bridge ทริป: KIA-1DAY / SYD-1DAY',
    'Unfenced cliff edges and strong wind. [REVIEW: primary related_trip_code KIA vs SYD.]',
    'หน้าผาไม่มีรั้ว ลมแรง [REVIEW: เลือกรหัสทริป KIA หรือ SYD]',
    'restricted',
    'Hang-glider airspace / cliffs — fly with extreme caution or not at all.',
    'KIA-1DAY',
    'KIA-1DAY',
    4.7,
    22,
    false,
    'Confirm preferred trip link (KIA day vs SYD day).',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111327'::uuid,
    'sea-cliff-bridge',
    'Sea Cliff Bridge',
    'สะพาน Sea Cliff Bridge',
    'Clifton / Coalcliff, NSW',
    'Clifton / Coalcliff, นิวเซาท์เวลส์',
    -34.25, 150.97,
    'https://maps.google.com/?q=Sea+Cliff+Bridge',
    'Iconic coastal bridge clinging to Illawarra cliffs — classic NSW south-coast drive photography.',
    'สะพานชายฝั่งเกาะหน้าผา Illawarra — จุดถ่ายภาพถนนชายฝั่งใต้ NSW คลาสสิก',
    array['Landscape','Coastal','Portrait'],
    'Morning side-light / blue hour',
    'Year-round',
    '~55–70 min from Sydney',
    'Lawrence Hargrave Drive; use signed pull-offs — do not stop in traffic lanes.',
    null,
    'Wide for bridge curve; mid from lookouts.',
    'People with bridge — stay off live lanes.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/250","filter":"CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Pair with Stanwell Tops. Trip: KIA-1DAY.',
    'คู่กับ Stanwell Tops ทริป: KIA-1DAY',
    'High-speed coastal road — only stop in safe bays. [REVIEW: best public lookout pin.]',
    'ถนนเร็ว — จอดเฉพาะจุดปลอดภัย [REVIEW: จุดชมวิวสาธารณะที่ดีที่สุด]',
    'restricted',
    'Road corridor and cliffs — avoid flying over traffic.',
    'KIA-1DAY',
    'KIA-1DAY',
    4.8,
    24,
    true,
    'Confirm safest public vantage pin.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111328'::uuid,
    'cowra-canola-fields',
    'Cowra & Canowindra Canola Fields',
    'ทุ่งคาโนลา Cowra & Canowindra',
    'Central West NSW',
    'ภาคกลางตะวันตก NSW',
    -33.83, 148.7,
    'https://maps.google.com/?q=Cowra+NSW+canola',
    'Seasonal golden canola fields around Cowra/Canowindra — peak colour is short and weather-dependent.',
    'ทุ่งคาโนลาสีทองตามฤดูกาลรอบ Cowra/Canowindra — ช่วงสีทองสั้นและขึ้นกับอากาศ',
    array['Landscape','Portrait','Nature'],
    'Peak bloom mornings (typically spring) [REVIEW exact weeks]',
    'Spring bloom only for classic yellow fields',
    '~3.5–4.5 hrs from Sydney',
    'Photograph from public roadsides only — never enter private paddocks without permission.',
    null,
    'Wide for field rows; mid for detail.',
    'Classic yellow-field portraits from fence lines.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–200","shutter":"1/250–1/500","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–400","shutter":"1/320+","filter":null}}'::jsonb,
    'Bloom windows move each year — check local updates. Trip: CAN-2D1N.',
    'ช่วงดอกบานเปลี่ยนทุกปี — เช็คข้อมูลท้องถิ่น ทริป: CAN-2D1N',
    'Private farmland. Soft road verges. [REVIEW: 2026 bloom timing & preferred roadside pin.]',
    'ที่นาส่วนตัว ไหล่ทางอ่อน [REVIEW: ช่วงดอกบาน 2026 และจุดจอด]',
    'restricted',
    'Private land — landowner permission required.',
    'CAN-2D1N',
    'CAN-2D1N',
    4.7,
    130,
    true,
    'Seasonal bloom — high REVIEW priority each year.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111329'::uuid,
    'cowra-canowindra-old-towns',
    'Cowra & Canowindra Old Towns',
    'เมืองเก่า Cowra & Canowindra',
    'Cowra / Canowindra, NSW',
    'Cowra / Canowindra, นิวเซาท์เวลส์',
    -33.835, 148.69,
    'https://maps.google.com/?q=Cowra+NSW',
    'Heritage main streets and country-town architecture in the Central West — pair with canola season trips.',
    'ถนนหลักมรดกและสถาปัตยกรรมเมืองชนบทภาคกลางตะวันตก — คู่กับทริปทุ่งคาโนลา',
    array['Portrait','Landscape'],
    'Soft morning / late afternoon street light',
    'Year-round; spring pairs with canola',
    '~3.5–4.5 hrs from Sydney',
    'Town street parking; walk main streets.',
    null,
    'Standard zoom for streetscapes.',
    '35–85mm for people with heritage shopfronts.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–400","shutter":"1/125–1/250","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–800","shutter":"1/200+","filter":null}}'::jsonb,
    'Ask before photographing people closely. Trip: CAN-2D1N.',
    'ขออนุญาตก่อนถ่ายคนระยะใกล้ ทริป: CAN-2D1N',
    'Quiet towns — be respectful. [REVIEW: Canowindra vs Cowra as primary pin.]',
    'เมืองเงียบ — เคารพผู้อยู่อาศัย [REVIEW: จุดหลัก Canowindra หรือ Cowra]',
    'restricted',
    'Town centre — avoid flying over people.',
    'CAN-2D1N',
    'CAN-2D1N',
    4.5,
    132,
    false,
    'Cluster pin at Cowra — may split towns later.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111330'::uuid,
    'cowra-japanese-garden',
    'Cowra Japanese Garden & Cultural Centre',
    'สวนญี่ปุ่นและศูนย์วัฒนธรรม Cowra',
    'Cowra, NSW',
    'Cowra, นิวเซาท์เวลส์',
    -33.828, 148.705,
    'https://maps.google.com/?q=Cowra+Japanese+Garden',
    'Large Japanese garden with ponds, bridges, and seasonal colour — peaceful portrait and landscape frames (ticketed).',
    'สวนญี่ปุ่นขนาดใหญ่มีบ่อ สะพาน และสีตามฤดู — เหมาะพอร์ตเทรตและแลนด์สเคป (มีตั๋ว)',
    array['Portrait','Landscape','Nature'],
    'Soft morning light; autumn maple colour [REVIEW]',
    'Year-round; autumn colour special',
    '~3.5–4 hrs from Sydney',
    'Ticketed garden — follow paths; do not enter garden beds.',
    null,
    'Wide–mid for ponds/bridges.',
    'Classic garden portraits — respectful, quiet.',
    '{"landscape":{"aperture":"f/5.6–f/8","iso":"100–200","shutter":"1/60–1/200","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–400","shutter":"1/160+","filter":null}}'::jsonb,
    'Check opening hours. Trip: CAN-2D1N.',
    'เช็คเวลาเปิด ทริป: CAN-2D1N',
    'Paths can be slippery after rain. [REVIEW: commercial photo permit policy.]',
    'ทางเดินลื่นหลังฝน [REVIEW: นโยบายถ่ายภาพเชิงพาณิชย์]',
    'prohibited',
    'Garden precinct — drones inappropriate without permission.',
    'CAN-2D1N',
    'CAN-2D1N',
    4.7,
    134,
    false,
    'Confirm ticket/hours and photo policy.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111331'::uuid,
    'sydney-northern-beaches',
    'Sydney Northern Beaches',
    'ชายหาดฝั่งเหนือซิดนีย์',
    'Palm Beach / Northern Beaches, NSW',
    'Palm Beach / ชายหาดฝั่งเหนือ, นิวเซาท์เวลส์',
    -33.6, 151.323,
    'https://maps.google.com/?q=Palm+Beach+NSW',
    'Palm Beach / Barrenjoey area — northern beaches coastal and headland frames (split from broad “Sydney locations”).',
    'ย่าน Palm Beach / Barrenjoey — วิวชายฝั่งและหัวหาดฝั่งเหนือ (แยกจาก “จุดซิดนีย์” กว้าง ๆ)',
    array['Coastal','Portrait','Landscape','Sunrise'],
    'Sunrise on east-facing beaches / late light on Barrenjoey',
    'Year-round; check surf conditions',
    '~1–1.5 hrs from Sydney CBD',
    'Beach car parks; Barrenjoey Lighthouse track is a walk — allow time.',
    'Buses to Northern Beaches (longer).',
    'Wide for beach/headland; ND for long exposure.',
    'Classic beach portraits — soft morning light.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND / CPL"},"portrait":{"aperture":"f/2–f/2.8","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Barrenjoey track: footwear and water. Trip: SYD-1DAY.',
    'เส้นทาง Barrenjoey: รองเท้าและน้ำ ทริป: SYD-1DAY',
    'Rips and dumpers — swim between flags. [REVIEW: Barrenjoey track difficulty/closures.]',
    'คลื่นและกระแสน้ำ — ว่ายน้ำในเขตธง [REVIEW: ความยาก/ปิดทาง Barrenjoey]',
    'restricted',
    'Crowded beaches — CASA rules; avoid flying over people.',
    'SYD-1DAY',
    'SYD-1DAY',
    4.8,
    26,
    true,
    'Split from curated #40 Sydney North — pin at Palm Beach.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111332'::uuid,
    'sydney-harbour-south-head',
    'Sydney Harbour — South Head & Watsons Bay',
    'อ่าวซิดนีย์ — South Head และ Watsons Bay',
    'Watsons Bay / South Head, NSW',
    'Watsons Bay / South Head, นิวเซาท์เวลส์',
    -33.833, 151.28,
    'https://maps.google.com/?q=South+Head,+Watsons+Bay',
    'Harbour entrance cliffs, The Gap, and Watsons Bay foreshore — classic Sydney Harbour south-side frames (split from broad Sydney list).',
    'หน้าผาปากอ่าว The Gap และริมน้ำ Watsons Bay — วิวอ่าวซิดนีย์ฝั่งใต้คลาสสิก',
    array['Coastal','Landscape','Portrait','Sunset'],
    'Late afternoon harbour light / sunset',
    'Year-round',
    '~25–40 min from Sydney CBD',
    'Watsons Bay parking (busy weekends); coastal walks to South Head.',
    'Ferry to Watsons Bay.',
    'Wide for cliffs/harbour; mid for Opera House distant frames [REVIEW conditions].',
    'People with harbour backdrop — cliff safety first.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/250","filter":"CPL"},"portrait":{"aperture":"f/2–f/2.8","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Ferry approach is scenic. Trip: SYD-1DAY.',
    'เรือเฟอร์รี่ทางเข้าสวย ทริป: SYD-1DAY',
    'Cliff edges at The Gap — stay behind fences. [REVIEW: sensitive site etiquette at The Gap.]',
    'หน้าผา The Gap — อยู่หลังรั้ว [REVIEW: มารยาทในพื้นที่อ่อนไหว]',
    'restricted',
    'Harbour / sensitive cliff areas — often unsuitable.',
    'SYD-1DAY',
    'SYD-1DAY',
    4.8,
    28,
    true,
    'Split from curated #40 Sydney South — pin Watsons Bay / South Head.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111333'::uuid,
    'long-jetty',
    'Long Jetty',
    'ท่าเรือ Long Jetty',
    'Long Jetty / The Entrance, NSW',
    'Long Jetty / The Entrance, นิวเซาท์เวลส์',
    -33.359, 151.482,
    'https://maps.google.com/?q=Long+Jetty+NSW',
    'Central Coast lakeside jetty and Tuggerah Lake reflections — calm sunrise/sunset water frames.',
    'ท่าเรือริมทะเลสาบ Central Coast และเงาสะท้อน Tuggerah Lake — วิวน้ำยามเช้า/เย็นที่สงบ',
    array['Landscape','Portrait','Sunrise','Sunset'],
    'Sunrise / sunset reflections',
    'Year-round; calm mornings best',
    '~1.5 hrs from Sydney',
    'Street/park access near the jetty foreshore.',
    null,
    'Wide for jetty leading lines; ND optional.',
    'People on jetty — watch slippery timber.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/160+","filter":null}}'::jsonb,
    'Pair with Central Coast day drives. Trip: SYD-1DAY. [REVIEW: dedicated Central Coast trip code if added later.]',
    'คู่กับทริป Central Coast ทริป: SYD-1DAY [REVIEW: รหัสทริปเฉพาะถ้ามีภายหลัง]',
    'Jetty timber can be slippery. [REVIEW: fishing traffic / best public parking pin.]',
    'ไม้ท่าเรือลื่นได้ [REVIEW: คนตกปลา / จุดจอด]',
    'restricted',
    'Follow CASA; avoid flying over people on the jetty.',
    'SYD-1DAY',
    'SYD-1DAY',
    4.6,
    136,
    false,
    'Confirm primary parking pin.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111334'::uuid,
    'catherine-hill-bay',
    'Catherine Hill Bay',
    'Catherine Hill Bay',
    'Catherine Hill Bay, NSW',
    'Catherine Hill Bay, นิวเซาท์เวลส์',
    -33.158, 151.629,
    'https://maps.google.com/?q=Catherine+Hill+Bay+NSW',
    'Heritage jetty and surf beach north of Sydney — coastal village atmosphere with classic pier leading lines.',
    'ท่าเรือมรดกและหาดเซิร์ฟทางเหนือซิดนีย์ — บรรยากาศหมู่บ้านชายฝั่งกับเส้นนำสายตาจากท่าเรือ',
    array['Coastal','Landscape','Portrait','Sunrise'],
    'Sunrise / soft morning side-light on the jetty',
    'Year-round; check surf/swell',
    '~1.5–2 hrs from Sydney',
    'Village parking; beach and jetty access on foot.',
    null,
    'Wide for jetty; ND for long exposure swells when safe.',
    'People with pier/beach — never turn back on dumpers.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/60–several sec with ND","filter":"ND / CPL"},"portrait":{"aperture":"f/2.8–f/4","iso":"100–400","shutter":"1/200+","filter":null}}'::jsonb,
    'Heritage jetty — treat with care. Trip: SYD-1DAY.',
    'ท่าเรือมรดก — ใช้อย่างระมัดระวัง ทริป: SYD-1DAY',
    'Powerful surf and rock platforms. [REVIEW: jetty access status / any closures.]',
    'คลื่นแรงและแท่นหิน [REVIEW: สถานะการขึ้นท่าเรือ/การปิด]',
    'restricted',
    'Follow CASA; crowded beach days — avoid over people.',
    'SYD-1DAY',
    'SYD-1DAY',
    4.7,
    138,
    false,
    'Confirm jetty structural access status.',
    null, null, '{}'::text[]
  ),
(
    'a1111111-1111-4111-8111-111111111335'::uuid,
    'anna-bay-sand-dunes',
    'Anna Bay Sand Dunes',
    'เนินทราย Anna Bay',
    'Anna Bay / Stockton Bight, NSW',
    'Anna Bay / Stockton Bight, นิวเซาท์เวลส์',
    -32.78, 152.085,
    'https://maps.google.com/?q=Anna+Bay+Sand+Dunes',
    'Vast Stockton Bight sand dunes near Anna Bay — desert-like portrait and landscape frames on the NSW coast.',
    'เนินทราย Stockton Bight ใกล้ Anna Bay — วิวคล้ายทะเลทรายบนชายฝั่ง NSW สำหรับพอร์ตเทรตและแลนด์สเคป',
    array['Landscape','Portrait','Nature'],
    'Golden hour (cooler sand, longer shadows)',
    'Year-round; avoid extreme midday heat',
    '~2.5–3 hrs from Sydney',
    'Signed dune access / tour operators for deep dunes. Stay off vegetated areas.',
    null,
    'Wide lens; protect camera from sand.',
    'Classic dune portraits — morning/evening light.',
    '{"landscape":{"aperture":"f/8–f/11","iso":"100–200","shutter":"1/125–1/500","filter":null},"portrait":{"aperture":"f/1.8–f/2.8","iso":"100–400","shutter":"1/320+","filter":null}}'::jsonb,
    'Seal camera bags against sand. Trip: LAV-ANB-1D.',
    'กันทรายเข้ากระเป๋ากล้อง ทริป: LAV-ANB-1D',
    'Heat, dehydration, and getting lost in dune fields. 4WD/tour areas can be hazardous. [REVIEW: public foot access vs tour-only zones.]',
    'ร้อน ขาดน้ำ และหลงในเนินทราย โซน 4WD อันตรายได้ [REVIEW: เข้าเดินเท้าได้หรือต้องทัวร์]',
    'restricted',
    'Follow CASA; avoid disturbing wildlife and people.',
    'LAV-ANB-1D',
    'LAV-ANB-1D',
    4.8,
    140,
    true,
    'Confirm public access boundaries vs commercial quad tours.',
    null, null, '{}'::text[]
  )
on conflict (slug) do update set
  title_en = excluded.title_en,
  title_th = excluded.title_th,
  location_en = excluded.location_en,
  location_th = excluded.location_th,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  google_maps_url = excluded.google_maps_url,
  description_en = excluded.description_en,
  description_th = excluded.description_th,
  categories = excluded.categories,
  best_time = excluded.best_time,
  best_season = excluded.best_season,
  drive_time_from_sydney = excluded.drive_time_from_sydney,
  access_private_car = excluded.access_private_car,
  access_public_transport = excluded.access_public_transport,
  gear_landscape = excluded.gear_landscape,
  gear_portrait = excluded.gear_portrait,
  camera_settings = excluded.camera_settings,
  tips_en = excluded.tips_en,
  tips_th = excluded.tips_th,
  warnings_en = excluded.warnings_en,
  warnings_th = excluded.warnings_th,
  drone_allowed = excluded.drone_allowed,
  drone_notes = excluded.drone_notes,
  linked_trip_code = excluded.linked_trip_code,
  related_trip_code = excluded.related_trip_code,
  rating = excluded.rating,
  sort_order = excluded.sort_order,
  is_featured = excluded.is_featured,
  review_notes = excluded.review_notes,
  updated_at = now();
-- note: hero_image_url / thumbnail_url / gallery_image_urls intentionally NOT overwritten on conflict
-- so staff-uploaded photos are preserved when re-running this seed.
