/** Local brand assets — generated by `node scripts/generate-brand-assets.mjs`. */
export const BRAND_BADGE_SRC = '/brand/trip2talk-badge.webp'
export const BRAND_BADGE_PNG_SRC = '/brand/trip2talk-badge.png'
export const BRAND_OG_SRC = '/brand/trip2talk-og.jpg'
export const BRAND_NAME = 'Trip2Talk'
